"""Schemas Module for SomaBrain API.

Submodules:
- memory: Memory operation schemas (RecallRequest, MemoryPayload, etc.)
- cognitive: Cognitive/planning schemas (ActRequest, Observation, etc.)
- health: Health, admin, and operational schemas (HealthResponse, etc.)
"""

# Memory schemas
# Cognitive schemas
from somabrain.schemas.cognitive import (
    Action,
    ActRequest,
    ActResponse,
    ActStepResult,
    Feedback,
    Memory,
    Metric,
    NeuromodStateModel,
    OakOptionCreateRequest,
    OakPlanSuggestResponse,
    Observation,
    Persona,
    PersonalityState,
    PlanStep,
    PlanSuggestRequest,
    PlanSuggestResponse,
    Thought,
    ToolCall,
)

# Health/Admin schemas
from somabrain.schemas.health import (
    ConfigResponse,
    FeatureFlagsResponse,
    FeatureFlagsUpdateRequest,
    FeatureFlagsUpdateResponse,
    HealthResponse,
    JournalReplayRequest,
    MigrateExportRequest,
    MigrateExportResponse,
    MigrateImportRequest,
    MigrateImportResponse,
    NeuromodAdjustRequest,
    OutboxEventModel,
    OutboxListResponse,
    OutboxReplayRequest,
    OutboxReplayResponse,
    OutboxSummaryResponse,
    OutboxTenantListResponse,
    OutboxTenantReplayRequest,
    OutboxTenantReplayResponse,
    OutboxTenantSummary,
    ProxyRequest,
    QuotaAdjustRequest,
    QuotaAdjustResponse,
    QuotaListResponse,
    QuotaResetRequest,
    QuotaResetResponse,
    QuotaStatus,
    ReflectResponse,
    SleepRunRequest,
    SleepRunResponse,
    SleepStatusAllResponse,
    SleepStatusResponse,
)
from somabrain.schemas.memory import (
    DeleteRequest,
    DeleteResponse,
    GraphLinksRequest,
    GraphLinksResponse,
    LinkRequest,
    LinkResponse,
    MemoryPayload,
    RecallRequest,
    RecallResponse,
    RememberRequest,
    RememberResponse,
    RetrievalCandidate,
    RetrievalRequest,
    RetrievalResponse,
    TimestampInput,
    WMHit,
    _get_settings,
    normalize_vector,
)

__all__ = [
    # Memory
    "RecallRequest",
    "MemoryPayload",
    "RememberRequest",
    "WMHit",
    "RecallResponse",
    "RememberResponse",
    "RetrievalRequest",
    "RetrievalCandidate",
    "RetrievalResponse",
    "DeleteRequest",
    "DeleteResponse",
    "LinkRequest",
    "GraphLinksRequest",
    "GraphLinksResponse",
    "LinkResponse",
    "TimestampInput",
    "normalize_vector",
    "_get_settings",
    # Cognitive
    "Observation",
    "Thought",
    "Memory",
    "ToolCall",
    "PlanStep",
    "Action",
    "Feedback",
    "Metric",
    "ActRequest",
    "ActStepResult",
    "ActResponse",
    "PlanSuggestRequest",
    "PlanSuggestResponse",
    "OakOptionCreateRequest",
    "OakPlanSuggestResponse",
    "NeuromodStateModel",
    "PersonalityState",
    "Persona",
    # Health/Admin
    "HealthResponse",
    "SleepRunRequest",
    "SleepRunResponse",
    "SleepStatusResponse",
    "SleepStatusAllResponse",
    "FeatureFlagsResponse",
    "FeatureFlagsUpdateRequest",
    "FeatureFlagsUpdateResponse",
    "MigrateExportRequest",
    "MigrateExportResponse",
    "MigrateImportRequest",
    "MigrateImportResponse",
    "ReflectResponse",
    "OutboxEventModel",
    "OutboxListResponse",
    "OutboxReplayRequest",
    "OutboxReplayResponse",
    "OutboxTenantReplayRequest",
    "OutboxTenantReplayResponse",
    "OutboxTenantListResponse",
    "OutboxTenantSummary",
    "OutboxSummaryResponse",
    "QuotaStatus",
    "QuotaListResponse",
    "QuotaResetRequest",
    "QuotaResetResponse",
    "QuotaAdjustRequest",
    "QuotaAdjustResponse",
    "NeuromodAdjustRequest",
    "ProxyRequest",
    "ConfigResponse",
    "JournalReplayRequest",
]
