repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: ["ruff==0.7.1"]

  # Secret scanning to prevent accidental commits of credentials
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (scan for credentials)
        # You can generate a baseline with: detect-secrets scan > .secrets.baseline
        # args: ["--baseline", ".secrets.baseline"]

  # Local hooks to run quick project-specific checks before push
  - repo: local
    hooks:
      - id: run-critical-rag-tests
        name: Run critical RAG persistence tests (prevent bad push)
        entry: pytest -q tests/test_rag_integration_persist.py::test_rag_persist_and_links_local_backend -q -s
        language: system
        stages: [push]

# Optional: add other hooks as your CI requires
