global:
  resolve_timeout: 5m

route:
  receiver: "default"
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://localhost:5000/alert"
