# SomaBrain example configuration (Balanced profile)
# Copy to config.yaml to enable.

# Embeddings
embed_provider: tiny            # tiny|hrr|fde|transformer
embed_dim: 256
embed_dim_target_k: 0          # JL target dim (0 = disabled)
embed_cache_size: 0

# HRR (enable for HRR-first rerank and cleanup)
use_hrr: true
use_hrr_cleanup: false
hrr_dim: 8192
hrr_seed: 42

# Predictor
predictor_provider: mahal      # stub|mahal|slow
predictor_timeout_ms: 250

# HRR-first rerank (WM + LTM)
use_hrr_first: true
hrr_rerank_weight: 0.3
hrr_rerank_only_low_margin: true
rerank_margin_threshold: 0.05

# Diversity rerank (MMR)
use_diversity: true
diversity_method: mmr          # mmr|facility (facility placeholder)
diversity_k: 8
diversity_lambda: 0.5

# Adaptive salience
use_adaptive_salience: true
salience_target_store_rate: 0.20
salience_target_act_rate: 0.10
salience_adjust_step: 0.005

# Link decay (graph maintenance)
link_decay_factor: 0.98
link_min_weight: 0.05

# Index/Compression (backend hints; local backend may ignore unknown keys)
index_profile: balanced        # low_latency|balanced|high_recall
pq_m: 16
pq_bits: 8
opq_enabled: false
anisotropic_enabled: false
imi_cells: 2048
hnsw_M: 16
hnsw_efc: 100
hnsw_efs: 64

# Rate limits / quotas
rate_rps: 50
rate_burst: 100
write_daily_limit: 10000


# Auth
# For OIDC/JWT integration (Keycloak, Cognito, Auth0):
# Uncomment and set the following for production:
# auth_required: true
# jwt_public_key_path: /secrets/keycloak_public.pem
# jwt_issuer: https://keycloak.example.com/realms/somabrain
# jwt_audience: somabrain-agents
#
# For Cognito:
# jwt_public_key_path: /secrets/cognito_public.pem
# jwt_issuer: https://cognito-idp.<region>.amazonaws.com/<user-pool-id>
# jwt_audience: <app-client-id>
#
# For dev/test (HS256):
auth_required: true
api_token: "dev-token"
jwt_secret: "dev-secret"
jwt_issuer: somabrain
jwt_audience: agents
default_tenant: sandbox
sandbox_tenants:
  - sandbox
  - tenant-alpha
sandbox_tenants_file: config/sandbox.tenants.yaml

# Planner (optional)
use_planner: false
plan_max_steps: 5
plan_rel_types: depends_on,causes,part_of,motivates,related

# Microcircuits (optional)
use_microcircuits: false
micro_circuits: 1
micro_vote_temperature: 0.25

# Reflection
reflect_similarity_threshold: 0.35
reflect_min_cluster_size: 2
reflect_max_summaries: 5

# Memory backend
# The memory subsystem is HTTP-only. Run the external memory API
# service and configure the HTTP endpoint below.
namespace: somabrain_ns
memory_http_endpoint: http://localhost:9595

# Persistence (optional overrides)
postgres_dsn: postgresql://somabrain:somabrain@localhost:5432/somabrain
feedback_dsn: postgresql://somabrain:somabrain@localhost:5432/somabrain
token_ledger_dsn: postgresql://somabrain:somabrain@localhost:5432/somabrain

# Auth (optional)
auth_required: false
api_token: "my-secret-token"

# Demo endpoints (optional; off by default)
# expose_alt_memory_endpoints: false  # /fnom/* and /fractal/*
# expose_brain_demos: false           # /brain/* unified demo endpoints

# Minimal Public API
# When true, only essential endpoints are exposed externally:
#   GET  /health
#   POST /remember
#   POST /recall
#   POST /plan/suggest
#   POST /sleep/run
# Disable to access internal/diagnostic routes during development.
minimal_public_api: true

# -----
# Alternative presets (uncomment and override above if desired)

# Low-latency (phone/edge)
# use_hrr: false
# use_hrr_first: false
# use_diversity: false
# predictor_provider: stub
# use_adaptive_salience: false
# index_profile: low_latency

# High-recall (server)
# use_hrr: true
# use_hrr_first: true
# hrr_rerank_only_low_margin: false
# use_diversity: true
# diversity_k: 12
# predictor_provider: mahal
# use_adaptive_salience: true
# index_profile: high_recall
