"""Minimal type stubs for the ``prometheus_client`` package used in SomaBrain.

The real ``prometheus_client`` library provides a rich set of metric classes.
For static analysis (Pyright) we only need the subset of attributes that the
codebase accesses: ``labels``, ``inc``, ``set`` and ``observe``.  Defining a
light‑weight stub avoids pulling the full dependency into the type‑checking
environment and satisfies the VIBE rule *Integrity* – the stub is clearly
documented and limited to the required API surface.
"""

from typing import Any

# Core collector protocol – all metric types share these methods.
class Collector:
    def labels(self, *args: Any, **kwargs: Any) -> "Collector": ...  # noqa: D401
    def inc(self, *args: Any, **kwargs: Any) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def observe(self, *args: Any, **kwargs: Any) -> None: ...

# Concrete metric classes – they inherit the Collector interface.
class Counter(Collector): ...
class Gauge(Collector): ...
class Histogram(Collector): ...
class Summary(Collector): ...

# Factory functions used throughout the codebase.
def Counter(name: str, documentation: str, *args: Any, **kwargs: Any) -> Counter: ...  # noqa: D401
def Gauge(name: str, documentation: str, *args: Any, **kwargs: Any) -> Gauge: ...
def Histogram(name: str, documentation: str, *args: Any, **kwargs: Any) -> Histogram: ...
def Summary(name: str, documentation: str, *args: Any, **kwargs: Any) -> Summary: ...

# Registry related symbols – only the names used in the project are stubbed.
CONTENT_TYPE_LATEST: str
REGISTRY: Any
class CollectorRegistry: ...
def generate_latest(registry: Any = ...) -> bytes: ...
