name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -e somafractalmemory
          python -m pip install numpy redis fakeredis qdrant-client networkx prometheus-client httpx fastapi uvicorn pytest

      - name: Run smoke tests
        env:
          PYTHONPATH: .
        run: |
          python -m pytest -q

