"""
Type stubs for Django model managers and fields to resolve Pyright errors.
Django model managers like 'objects' are added dynamically at runtime.
Django model fields like CharField, IntegerField are dynamically typed.
"""
from typing import TypeVar, Generic, TYPE_CHECKING, overload

if TYPE_CHECKING:
    from django.db import models

    _T = TypeVar('_T')

    class Manager(Generic[_T]):
        """Base manager type stub."""
        def all(self) -> models.QuerySet[_T]: ...
        def filter(self, **kwargs: object) -> models.QuerySet[_T]: ...
        def get(self, **kwargs: object) -> _T: ...
        def create(self, **kwargs: object) -> _T: ...
        def get_or_create(self, **kwargs: object) -> tuple[_T, bool]: ...
        def update_or_create(self, **kwargs: object) -> tuple[_T, bool]: ...
        def count(self) -> int: ...
        def order_by(self, *fields: str) -> models.QuerySet[_T]: ...

    class QuerySet(Generic[_T]):
        """QuerySet type stub."""
        def all(self) -> models.QuerySet[_T]: ...
        def filter(self, **kwargs: object) -> models.QuerySet[_T]: ...
        def get(self, **kwargs: object) -> _T: ...
        def count(self) -> int: ...
        def first(self) -> _T | None: ...
        def last(self) -> _T | None: ...
        def exists(self) -> bool: ...
        def order_by(self, *fields: str) -> models.QuerySet[_T]: ...

    class Field:
        """Base field type stub with proper value access."""
        pass

    class CharField(Field, str):
        """CharField stub that acts like str."""
        def __add__(self, other: str) -> str: ...
        def split(self, sep: str = None) -> list[str]: ...
        def startswith(self, prefix: str) -> bool: ...
        def lower(self) -> str: ...
        def upper(self) -> str: ...
        def strip(self) -> str: ...
        def replace(self, old: str, new: str) -> str: ...

    class TextField(Field, str):
        """TextField stub that acts like str."""
        pass

    class IntegerField(Field, int):
        """IntegerField stub that acts like int."""
        @overload
        def __add__(self, other: int) -> int: ...
        @overload
        def __add__(self, other: int | str) -> int | str: ...
        def __gt__(self, other: int) -> bool: ...
        def __lt__(self, other: int) -> bool: ...

    class DateTimeField(Field):
        """DateTimeField stub with isoformat method."""
        def isoformat(self) -> str: ...

    class JSONField(Field, dict):
        """JSONField stub that acts like dict."""
        def get(self, key: str, default = None) -> object: ...
        def __getitem__(self, key: str) -> object: ...
