"""
Type stubs for hypothesis to resolve Pyright import errors.
"""

from typing import TypeVar, Any, Callable, ParamSpec

P = ParamSpec("P")
T = TypeVar("T")

def given(*given_args: Any, **given_kwargs: Any) -> Callable[[Callable[P, T]], Callable[P, T]]: ...
def settings(**settings_kwargs: Any) -> Any: ...
def strategies(module: str) -> Any: ...
def assume(condition: bool | Callable[[], bool]) -> None: ...
