_format_version: "3.0"
_transform: true

services:
  - name: somabrain-memory-service
    url: {{ env "SOMABRAIN_MEMORY_UPSTREAM" | default "http://somabrain-memory.default.svc.cluster.local:8080" }}
    routes:
      - name: somabrain-memory-route
        paths:
          - /memory
        strip_path: false
        methods: ["GET", "POST"]
        request_buffering: false
        response_buffering: false
        plugins:
          - name: jwt
            config:
              key_claim_name: iss
              claims_to_verify:
                - exp
              header_names:
                - Authorization
              secret_is_base64: false
              run_on_preflight: true
          - name: rate-limiting
            config:
              policy: redis
              redis_host: {{ env "SOMABRAIN_REDIS_HOST" | default "redis.svc.cluster.local" }}
              redis_port: {{ env "SOMABRAIN_REDIS_PORT" | default "6379" }}
              minute: {{ env "SOMABRAIN_RATE_LIMIT_PER_MIN" | default "3000" }}
              limit_by: consumer
          - name: request-transformer
            config:
              add:
                headers:
                  - X-Gateway-Route:memory-edge
          - name: prometheus
          - name: file-log
            config:
              path: {{ env "SOMABRAIN_GATEWAY_LOG_PATH" | default "/var/log/kong/memory-edge.log" }}
              reopen: true

plugins:
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true
