# Stub type definitions for the SQLAlchemy library used in this project.
# Source: https://docs.sqlalchemy.org/en/20/orm/mapping_api.html
from typing import Any

class Column:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Integer: ...
class String: ...
class Text: ...
class DateTime: ...

class func:
    @staticmethod
    def now() -> Any: ...

class orm:
    class Session:
        def __init__(self, bind: Any = ...) -> None: ...
        def add(self, instance: Any) -> None: ...
        def commit(self) -> None: ...
        def rollback(self) -> None: ...
        def close(self) -> None: ...

def declarative_base() -> Any: ...
def create_engine(url: str, **kwargs: Any) -> Any: ...
