# Generated by Django 6.0.1 on 2026-01-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrainSetting',
        ),
    ]
