apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: metallb-system
  name: metallb-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: metallb-system
  name: metallb-speaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-system:controller
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "nodes", "pods", "secrets"]
  verbs: ["list", "watch", "get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-system:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-system:controller
subjects:
- kind: ServiceAccount
  name: metallb-controller
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-system:speaker
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "nodes", "pods"]
  verbs: ["list", "watch", "get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-system:speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-system:speaker
subjects:
- kind: ServiceAccount
  name: metallb-speaker
  namespace: metallb-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metallb-system
  name: controller
spec:
  selector:
    matchLabels:
      component: controller
  replicas: 1
  template:
    metadata:
      labels:
        component: controller
    spec:
      serviceAccountName: metallb-controller
      containers:
      - name: controller
        image: quay.io/metallb/controller:v0.12.1
        args:
        - --config=namespace=metallb-system
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: metallb-system
  name: speaker
spec:
  selector:
    matchLabels:
      component: speaker
  template:
    metadata:
      labels:
        component: speaker
    spec:
      serviceAccountName: metallb-speaker
      hostNetwork: true
      containers:
      - name: speaker
        image: quay.io/metallb/speaker:v0.12.1
        args:
        - --port=7472
        env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_NODE_SELECTOR
          value: ""
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      # Adjust the IP range to match your kind cluster's Docker network.
      # The default kind network is 172.18.0.0/16. Choose a free range.
      addresses:
      - 172.18.255.200-172.18.255.250
