# Generated by Django 6.0 on 2025-12-24 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CognitiveThread",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "thread_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "cognitive_threads",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="cognitive_t_tenant__248af9_idx",
                    ),
                    models.Index(
                        fields=["thread_id"], name="cognitive_t_thread__33ff7a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="cognitive_t_created_f2863c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConstitutionSignature",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("checksum", models.CharField(db_index=True, max_length=128)),
                ("signer_id", models.CharField(max_length=128)),
                ("signature", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "constitution_signatures",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["checksum", "created_at"],
                        name="constitutio_checksu_f09931_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("checksum", "signer_id"),
                        name="uq_constitution_signature",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConstitutionVersion",
            fields=[
                (
                    "checksum",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("document", models.JSONField()),
                (
                    "metadata",
                    models.JSONField(blank=True, db_column="metadata", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "constitution_versions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="constitutio_is_acti_9f5cd0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EpisodicSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("namespace", models.CharField(blank=True, max_length=255, null=True)),
                ("key", models.CharField(max_length=500)),
                ("value", models.JSONField()),
                ("tags", models.JSONField(blank=True, null=True)),
                ("policy_tags", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "episodic_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "namespace", "key"],
                        name="episodic_sn_tenant__3b6750_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "created_at"],
                        name="episodic_sn_tenant__804180_idx",
                    ),
                    models.Index(fields=["key"], name="episodic_sn_key_771faf_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "feedback_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "feedback_records",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "timestamp"],
                        name="feedback_re_tenant__f987e4_idx",
                    ),
                    models.Index(
                        fields=["feedback_type"], name="feedback_re_feedbac_4b93ee_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="feedback_re_rating_895e0c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=50),
                ),
                ("retries", models.IntegerField(default=0)),
                ("dedupe_key", models.CharField(max_length=255)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "tenant_id", "created_at"],
                        name="ix_outbox_stt",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "dedupe_key"),
                        name="uq_outbox_tenant_dedupe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SleepState",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("state", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("cycle_number", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "sleep_states",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "timestamp"],
                        name="sleep_state_tenant__b1f7bd_idx",
                    ),
                    models.Index(fields=["state"], name="sleep_state_state_23ee7a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TokenLedger",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("operation", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "token_ledger",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "timestamp"],
                        name="token_ledge_tenant__733bdf_idx",
                    ),
                    models.Index(
                        fields=["endpoint"], name="token_ledge_endpoin_9ecd01_idx"
                    ),
                ],
            },
        ),
    ]
