# Generated by Django 5.1.4 on 2025-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("somabrain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSleepState",
            fields=[
                (
                    "tenant_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("current_state", models.CharField(default="active", max_length=50)),
                ("target_state", models.CharField(default="active", max_length=50)),
                ("last_transition", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ttl", models.DateTimeField(blank=True, null=True)),
                ("scheduled_wake", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tenant_sleep_states",
            },
        ),
    ]
