# Stub type definitions for the real Milvus Python SDK.
# Source: https://milvus.io/docs/v2.4.x/sdk_reference/python/Collection.md
from typing import Any, List, Dict, Optional

class Collection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def load(self) -> None: ...
    def release(self) -> None: ...
    def delete(self, expr: str) -> None: ...
    def query(self, expr: str, *args: Any, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def create_index(self, field_name: str, index_params: Dict[str, Any]) -> None: ...
    @property
    def indexes(self) -> List[Any]: ...

class FieldSchema:
    def __init__(self, name: str, dtype: Any, **kwargs: Any) -> None: ...

class CollectionSchema:
    def __init__(self, fields: List[FieldSchema], **kwargs: Any) -> None: ...

class DataType:
    VARCHAR: Any
    FLOAT_VECTOR: Any
    INT64: Any

class _Conn:
    @staticmethod
    def connect(host: str, port: int, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def disconnect() -> None: ...
    @staticmethod
    def get_connection_addr() -> str: ...
    @staticmethod
    def get_connection() -> Any: ...

class _Util:
    @staticmethod
    def has_collection(name: str) -> bool: ...
    @staticmethod
    def create_collection(name: str, schema: CollectionSchema, **kwargs: Any) -> None: ...
    @staticmethod
    def drop_collection(name: str) -> None: ...
    @staticmethod
    def get_collection_stats(name: str) -> Dict[str, Any]: ...

connections = _Conn()
utility = _Util()