from typing import Callable, Any, Optional, Union

class Etcd3Client:
    def get(self, key: Union[str, bytes]) -> Optional[Union[str, bytes]]: ...
    def put(self, key: Union[str, bytes], value: Union[str, bytes]) -> None: ...
    def delete(self, key: Union[str, bytes]) -> None: ...
    def add_watch_prefix_callback(
        self, prefix: Union[str, bytes], cb: Callable[..., Any]
    ) -> int: ...
    def cancel_watch(self, watch_id: int) -> None: ...

def client(
    host: str = ..., port: int = ..., timeout: Optional[float] = ...
) -> Etcd3Client: ...
