from typing import Any


class Response:
	status_code: int
	text: str

	def json(self) -> Any: ...

	def raise_for_status(self) -> None: ...


def get(url: str, **kwargs) -> Response: ...


class Session:
	def post(self, url: str, **kwargs) -> Response: ...

	def get(self, url: str, **kwargs) -> Response: ...

	def delete(self, url: str, **kwargs) -> Response: ...

def session() -> Session: ...


def post(url: str, **kwargs) -> Response: ...


def delete(url: str, **kwargs) -> Response: ...
