{{- if and .Values.memory (or .Values.memory.createSecret .Values.memory.token .Values.memory.endpoint) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soma-apps.memorySecretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "soma-apps.labels" (dict "root" . "component" "sb") | indent 4 }}
stringData:
  SOMABRAIN_MEMORY_HTTP_TOKEN: {{ default "" .Values.memory.token | quote }}
  SOMABRAIN_MEMORY_HTTP_ENDPOINT: {{ default "" .Values.memory.endpoint | quote }}
{{- end }}
