{{- if .Values.predictorAction.enabled }}
{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soma-apps.componentName" (dict "root" $root "component" "pred-action") }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
{{ include "soma-apps.labels" (dict "root" $root "component" "pred-action") | indent 4 }}
spec:
  replicas: {{ .Values.predictorAction.replicaCount }}
  selector:
    matchLabels:
{{ include "soma-apps.labels" (dict "root" $root "component" "pred-action") | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soma-apps.labels" (dict "root" $root "component" "pred-action") | indent 8 }}
    spec:
      containers:
        - name: predictor-action
          image: "{{ .Values.predictorAction.image.repository }}:{{ .Values.predictorAction.image.tag }}"
          imagePullPolicy: {{ .Values.predictorAction.image.pullPolicy | default $root.Values.global.imagePullPolicy }}
          command: ["python3"]
          args: ["/app/services/predictor-action/main.py"]
          env:
{{- range $key, $value := $root.Values.envCommon }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
{{- range $key, $value := .Values.predictorAction.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
{{- end }}
