{{- if .Values.segmentation.enabled }}
{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soma-apps.componentName" (dict "root" $root "component" "segmentation") }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
{{ include "soma-apps.labels" (dict "root" $root "component" "segmentation") | indent 4 }}
spec:
  replicas: {{ .Values.segmentation.replicaCount }}
  selector:
    matchLabels:
{{ include "soma-apps.labels" (dict "root" $root "component" "segmentation") | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soma-apps.labels" (dict "root" $root "component" "segmentation") | indent 8 }}
    spec:
      {{- if .Values.securityContext.pod.enabled }}
      securityContext:
{{ include "soma-apps.podSecurityContext" . | indent 8 }}
      {{- end }}
      containers:
        - name: segmentation
          image: "{{ .Values.segmentation.image.repository }}:{{ .Values.segmentation.image.tag }}"
          imagePullPolicy: {{ .Values.segmentation.image.pullPolicy | default $root.Values.global.imagePullPolicy }}
          command: ["python3"]
          args: ["-m", "somabrain.services.segmentation_service"]
          ports:
            - containerPort: 8092
              name: health
          {{- if .Values.securityContext.container.enabled }}
          securityContext:
{{ include "soma-apps.containerSecurityContext" . | indent 12 }}
          {{- end }}
          env:
{{- range $key, $value := $root.Values.envCommon }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
            - name: ENABLE_COG_THREADS
              value: "{{ ternary "1" "0" $root.Values.featureFlags.enableCogThreads }}"
{{- range $key, $value := .Values.segmentation.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
            - name: HEALTH_PORT
              value: "8092"
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
{{ toYaml .Values.segmentation.resources | indent 12 }}
{{- end }}
