## Staging overrides for soma-infra

# Override mode for staging environment
envCommon:
  SOMABRAIN_MODE: "staging"

auth:
  replicaCount: 2

opa:
  replicaCount: 2

kafka:
  replicaCount: 3

redis:
  architecture: standalone

etcd:
  replicaCount: 3

vault:
  server:
    standalone:
      enabled: true

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d

configHash: "staging"
