## Development overrides for local iteration

# Turn on localDev helper which enables dev annotations and quick iteration
localDev: true

# Components to bring up in a lightweight local/dev cluster
auth:
  enabled: false

opa:
  enabled: true

redis:
  enabled: true

kube-prometheus-stack:
  enabled: false

# Example configHash for forcing rolling updates during dev iterations
configHash: "dev"

# Notes: Use `helm upgrade --install soma-infra ./infra/helm/charts/soma-infra -f infra/helm/charts/soma-infra/values-dev.yaml`
#+ to apply dev overrides when testing in a local k8s cluster (minikube / kind).
