"""Module 0002_auth_identity_providers."""

# Generated by Django 6.0 on 2025-12-25 02:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class implementation."""

    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("keycloak", "Keycloak"),
                            ("google", "Google OAuth"),
                            ("facebook", "Facebook OAuth"),
                            ("github", "GitHub OAuth"),
                            ("oidc", "Generic OIDC"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("client_id", models.CharField(max_length=500)),
                ("project_id", models.CharField(blank=True, max_length=255, null=True)),
                ("auth_uri", models.URLField(max_length=500)),
                ("token_uri", models.URLField(max_length=500)),
                ("certs_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "redirect_uris",
                    models.JSONField(default=list, help_text="Allowed redirect URIs"),
                ),
                ("javascript_origins", models.JSONField(blank=True, default=list)),
                (
                    "default_scopes",
                    models.JSONField(
                        default=list, help_text="e.g. ['openid', 'email', 'profile']"
                    ),
                ),
                (
                    "claim_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map provider claims to our fields: {'tenant_id': 'custom:tenant_id'}",
                    ),
                ),
                (
                    "vault_secret_path",
                    models.CharField(
                        help_text="e.g. vault://secrets/oauth/google/client_secret",
                        max_length=500,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default login provider"
                    ),
                ),
                ("trust_email", models.BooleanField(default=True)),
                ("store_token", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = platform-level provider",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_providers",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Provider",
                "verbose_name_plural": "Identity Providers",
                "db_table": "saas_identity_providers",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted"
                    ),
                ),
                (
                    "platform_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("super-admin", "Super Admin"),
                            ("tenant-admin", "Tenant Admin"),
                            ("tenant-user", "Tenant User"),
                            ("api-access", "API Access"),
                        ],
                        help_text="Maps to platform role hierarchy",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="saas.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "saas_roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("can_view", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to="saas.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Permission",
                "verbose_name_plural": "Field Permissions",
                "db_table": "saas_field_permissions",
            },
        ),
        migrations.CreateModel(
            name="TenantAuthConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("custom_redirect_uris", models.JSONField(blank=True, default=list)),
                ("require_mfa", models.BooleanField(default=False)),
                ("session_timeout_minutes", models.IntegerField(default=60)),
                ("custom_claim_mappings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_by_tenants",
                        to="saas.identityprovider",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_config",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Auth Config",
                "verbose_name_plural": "Tenant Auth Configs",
                "db_table": "saas_tenant_auth_config",
            },
        ),
        migrations.CreateModel(
            name="TenantUserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="saas.role",
                    ),
                ),
                (
                    "tenant_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="saas.tenantuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant User Role",
                "verbose_name_plural": "Tenant User Roles",
                "db_table": "saas_tenant_user_roles",
            },
        ),
        migrations.AddConstraint(
            model_name="identityprovider",
            constraint=models.UniqueConstraint(
                fields=("tenant", "provider_type", "name"), name="uq_identity_provider"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpermission",
            index=models.Index(
                fields=["role", "model_name"], name="saas_field__role_id_9326b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldpermission",
            constraint=models.UniqueConstraint(
                fields=("role", "model_name", "field_name"), name="uq_field_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantuserrole",
            constraint=models.UniqueConstraint(
                fields=("tenant_user", "role"), name="uq_tenant_user_role"
            ),
        ),
    ]
