"""Module 0003_alter_tenant_tier_tenantsubscription_usagerecord."""

# Generated by Django 6.0 on 2025-12-25 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    """Migration class implementation."""

    dependencies = [
        ("saas", "0002_auth_identity_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                    ("system", "System"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lago_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lago_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_subscriptions",
                        to="saas.tenant",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tier_subscriptions",
                        to="saas.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Subscription",
                "verbose_name_plural": "Tenant Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "lago_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("synced_to_lago", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "recorded_at"],
                        name="saas_usager_tenant__1de76c_idx",
                    ),
                    models.Index(
                        fields=["metric_name", "recorded_at"],
                        name="saas_usager_metric__0fb935_idx",
                    ),
                ],
            },
        ),
    ]