#!/usr/bin/env bash
set -euo pipefail
# dev_up.sh - single canonical helper to start the dev stack
# Behavior:
# - Detect free host ports for key services (if default port in use, pick next free)
# - Write .env.local with chosen host port mappings
# - Start docker compose with docker-compose.yml using .env.local
# - Wait for somabrain health endpoint and write ports.json for testers

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

# Default memory endpoint (use host.docker.internal for macOS, fall back to localhost)
MEMORY_ENDPOINT=${SOMABRAIN_MEMORY_HTTP_ENDPOINT:-http://host.docker.internal:9595}
MEMORY_BASE=${MEMORY_ENDPOINT%:*}
if [[ "$MEMORY_BASE" == "http" || "$MEMORY_BASE" == "$MEMORY_ENDPOINT" ]]; then
    MEMORY_BASE=$MEMORY_ENDPOINT
fi

ENVFILE=.env.local
echo "# Generated by scripts/dev_up.sh" > $ENVFILE
echo "COMPOSE_PROJECT_NAME=somabrain" >> $ENVFILE

# Function to find next available port starting from a given port
find_free_port() {
    local start_port=$1
    local port=$start_port
    while lsof -i :$port >/dev/null 2>&1; do
        ((port++))
        if [ $port -gt 65535 ]; then
            echo "ERROR: No available ports found starting from $start_port" >&2
            return 1
        fi
    done
    echo $port
}

# Fixed container ports, host ports allocated from 30000+ range
REDIS_PORT=$(find_free_port 30000)
KAFKA_BROKER_PORT=$(find_free_port 30001)
KAFKA_EXPORTER_PORT=$(find_free_port 30003)
OPA_PORT=$(find_free_port 30004)
PROMETHEUS_PORT=$(find_free_port 30005)
POSTGRES_PORT=$(find_free_port 30006)
POSTGRES_EXPORTER_PORT=$(find_free_port 30007)
SOMABRAIN_PORT=9696
if lsof -i :$SOMABRAIN_PORT >/dev/null 2>&1; then
    echo "ERROR: SomaBrain API requires host port ${SOMABRAIN_PORT} but it is already in use." >&2
    exit 1
fi
MEMORY_PORT=$(find_free_port 30009)

echo "Port allocation (host ports):"
echo "  Redis: $REDIS_PORT"
echo "  Kafka Broker: $KAFKA_BROKER_PORT"
echo "  Kafka Exporter: $KAFKA_EXPORTER_PORT"
echo "  OPA: $OPA_PORT"
echo "  Prometheus: $PROMETHEUS_PORT"
echo "  Postgres: $POSTGRES_PORT"
echo "  Postgres Exporter: $POSTGRES_EXPORTER_PORT"
echo "  SomaBrain API: $SOMABRAIN_PORT (fixed)"
echo "  Memory Stub: $MEMORY_PORT"

# Write detected ports
cat <<PORTS >> $ENVFILE
REDIS_HOST_PORT=$REDIS_PORT
KAFKA_BROKER_HOST_PORT=$KAFKA_BROKER_PORT
KAFKA_EXPORTER_HOST_PORT=$KAFKA_EXPORTER_PORT
OPA_HOST_PORT=$OPA_PORT
PROMETHEUS_HOST_PORT=$PROMETHEUS_PORT
POSTGRES_HOST_PORT=$POSTGRES_PORT
POSTGRES_EXPORTER_HOST_PORT=$POSTGRES_EXPORTER_PORT
SOMABRAIN_HOST_PORT=$SOMABRAIN_PORT
SOMAMEMORY_HOST_PORT=$MEMORY_PORT
PORTS

# Ensure the memory endpoint points to the dynamically detected port
echo "SOMABRAIN_MEMORY_HTTP_ENDPOINT=http://host.docker.internal:$MEMORY_PORT" >> $ENVFILE

# Production-like defaults for development: strict-real and full stack
cat <<'FLAGS' >> $ENVFILE
SOMABRAIN_FORCE_FULL_STACK=1
SOMABRAIN_STRICT_REAL=1
SOMABRAIN_REQUIRE_MEMORY=1
SOMABRAIN_MODE=enterprise
SOMABRAIN_PREDICTOR_PROVIDER=mahal
FLAGS

echo "Wrote $ENVFILE:" && sed -n '1,200p' $ENVFILE

echo "Cleaning any previous compose state (down --remove-orphans)"
docker compose --env-file $ENVFILE -f docker-compose.yml down --remove-orphans || true
echo "Bringing up docker compose (this will build the somabrain image)..."
docker compose --env-file $ENVFILE -f docker-compose.yml up -d --build somabrain_app somabrain_outbox_publisher

# Wait for somabrain health
SOMABRAIN_PORT=$(grep '^SOMABRAIN_HOST_PORT=' $ENVFILE | cut -d= -f2)
echo "Waiting for somabrain on http://localhost:${SOMABRAIN_PORT}/health"
for i in $(seq 1 60); do
  if curl -fsS "http://localhost:${SOMABRAIN_PORT}/health" >/dev/null 2>&1; then
    echo "somabrain healthy"
    break
  fi
  sleep 2
done

echo "Writing ports.json"
python3 - <<PY
import json,subprocess
env={}
with open('.env.local') as f:
    for l in f:
        if '=' in l:
            k,v=l.strip().split('=',1)
            env[k]=v
ports={}
ports.update(env)
services=['somabrain_app','somabrain_redis','somabrain_kafka','somabrain_prometheus','somabrain_postgres','somabrain_kafka_exporter','somabrain_postgres_exporter','somabrain_opa']
port_map={'somabrain_app':'9696','somabrain_redis':'6379','somabrain_kafka':'9092','somabrain_prometheus':'9090','somabrain_postgres':'5432','somabrain_kafka_exporter':'9308','somabrain_postgres_exporter':'9187','somabrain_opa':'8181'}
for s in services:
    try:
        # Map each service to its container port for port lookup
        container_port = port_map[s]
        out=subprocess.check_output(['docker','compose','-f','docker-compose.yml','port',s,container_port], text=True).strip()
        ports[s+'_host_mapping']=out
    except Exception:
        ports[s+'_host_mapping']=''
open('ports.json','w').write(json.dumps(ports,indent=2))
print('wrote ports.json')
PY

echo "Done. Use ports.json for test harness or inspect with 'cat ports.json'"
