# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from somabrain.proto import brain_pb2 as somabrain_dot_proto_dot_brain__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in somabrain/proto/brain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
                '/soma.brain.v1.Brain/Remember',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.RememberRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.RememberBatch = channel.unary_unary(
                '/soma.brain.v1.Brain/RememberBatch',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.RememberBatchRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.RememberBatchResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/soma.brain.v1.Brain/Recall',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.RecallRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.RecallBatch = channel.unary_unary(
                '/soma.brain.v1.Brain/RecallBatch',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.RecallBatchRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.RecallBatchResponse.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/soma.brain.v1.Brain/Forget',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.ForgetRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.ForgetResponse.FromString,
                _registered_method=True)
        self.StreamContext = channel.unary_stream(
                '/soma.brain.v1.Brain/StreamContext',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.StreamContextRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.ContextEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/soma.brain.v1.Brain/Health',
                request_serializer=somabrain_dot_proto_dot_brain__pb2.HealthRequest.SerializeToString,
                response_deserializer=somabrain_dot_proto_dot_brain__pb2.HealthResponse.FromString,
                _registered_method=True)


class BrainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Remember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RememberBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecallBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.RememberRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.RememberResponse.SerializeToString,
            ),
            'RememberBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RememberBatch,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.RememberBatchRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.RememberBatchResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.RecallRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.RecallResponse.SerializeToString,
            ),
            'RecallBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RecallBatch,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.RecallBatchRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.RecallBatchResponse.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.ForgetRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.ForgetResponse.SerializeToString,
            ),
            'StreamContext': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamContext,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.StreamContextRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.ContextEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=somabrain_dot_proto_dot_brain__pb2.HealthRequest.FromString,
                    response_serializer=somabrain_dot_proto_dot_brain__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'soma.brain.v1.Brain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('soma.brain.v1.Brain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Brain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soma.brain.v1.Brain/Remember',
            somabrain_dot_proto_dot_brain__pb2.RememberRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RememberBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soma.brain.v1.Brain/RememberBatch',
            somabrain_dot_proto_dot_brain__pb2.RememberBatchRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.RememberBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soma.brain.v1.Brain/Recall',
            somabrain_dot_proto_dot_brain__pb2.RecallRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecallBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soma.brain.v1.Brain/RecallBatch',
            somabrain_dot_proto_dot_brain__pb2.RecallBatchRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.RecallBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soma.brain.v1.Brain/Forget',
            somabrain_dot_proto_dot_brain__pb2.ForgetRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.ForgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/soma.brain.v1.Brain/StreamContext',
            somabrain_dot_proto_dot_brain__pb2.StreamContextRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.ContextEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soma.brain.v1.Brain/Health',
            somabrain_dot_proto_dot_brain__pb2.HealthRequest.SerializeToString,
            somabrain_dot_proto_dot_brain__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
