# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x06memory\"J\n\rMemoryPayload\x12\x11\n\tcoord_key\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x15\n\rquality_score\x18\x03 \x01(\x01\"9\n\x0fRememberRequest\x12&\n\x07payload\x18\x01 \x01(\x0b\x32\x15.memory.MemoryPayload\"\x1e\n\x10RememberResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"-\n\rRecallRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"G\n\nRecallItem\x12\x11\n\tcoord_key\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x15\n\rquality_score\x18\x03 \x01(\x01\"3\n\x0eRecallResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.memory.RecallItem2\x87\x01\n\rMemoryService\x12=\n\x08Remember\x12\x17.memory.RememberRequest\x1a\x18.memory.RememberResponse\x12\x37\n\x06Recall\x12\x15.memory.RecallRequest\x1a\x16.memory.RecallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMORYPAYLOAD']._serialized_start=24
  _globals['_MEMORYPAYLOAD']._serialized_end=98
  _globals['_REMEMBERREQUEST']._serialized_start=100
  _globals['_REMEMBERREQUEST']._serialized_end=157
  _globals['_REMEMBERRESPONSE']._serialized_start=159
  _globals['_REMEMBERRESPONSE']._serialized_end=189
  _globals['_RECALLREQUEST']._serialized_start=191
  _globals['_RECALLREQUEST']._serialized_end=236
  _globals['_RECALLITEM']._serialized_start=238
  _globals['_RECALLITEM']._serialized_end=309
  _globals['_RECALLRESPONSE']._serialized_start=311
  _globals['_RECALLRESPONSE']._serialized_end=362
  _globals['_MEMORYSERVICE']._serialized_start=365
  _globals['_MEMORYSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
