from typing import Any, Optional

class SpanExporter: ...
class BatchSpanProcessor: ...
class ConsoleSpanExporter: ...

class OTLPSpanExporter:
    def __init__(
        self, endpoint: Optional[str] = ..., insecure: Optional[bool] = ...
    ) -> None: ...

def add_span_processor(p: Any) -> None: ...
