import environ  # type: ignore[import-untyped]

from .infra import KAFKA_BOOTSTRAP_SERVERS as _INFRA_KAFKA_BOOTSTRAP_SERVERS
from .infra import SOMABRAIN_MEMORY_HTTP_ENDPOINT as _INFRA_MEMORY_HTTP_ENDPOINT
from .infra import SOMABRAIN_MEMORY_HTTP_TOKEN
from .infra import _resolved

env = environ.Env()

# ============================================================================
# COGNITIVE & MEMORY SETTINGS
# ============================================================================

# --- COGNITIVE TOPICS ---
SOMABRAIN_TOPIC_NEXT_EVENT = env.str(
    "SOMABRAIN_TOPIC_NEXT_EVENT", default="cog.next_event"
)
SOMABRAIN_TOPIC_GLOBAL_FRAME = env.str(
    "SOMABRAIN_TOPIC_GLOBAL_FRAME", default="cog.global.frame"
)
SOMABRAIN_TOPIC_STATE_UPDATES = env.str(
    "SOMABRAIN_TOPIC_STATE_UPDATES", default="cog.state.updates"
)
SOMABRAIN_TOPIC_AGENT_UPDATES = env.str(
    "SOMABRAIN_TOPIC_AGENT_UPDATES", default="cog.agent.updates"
)
SOMABRAIN_TOPIC_ACTION_UPDATES = env.str(
    "SOMABRAIN_TOPIC_ACTION_UPDATES", default="cog.action.updates"
)
SOMABRAIN_TOPIC_CONFIG_UPDATES = env.str(
    "SOMABRAIN_TOPIC_CONFIG_UPDATES", default="cog.config.updates"
)
SOMABRAIN_TOPIC_SEGMENTS = env.str("SOMABRAIN_TOPIC_SEGMENTS", default="cog.segments")

# Lowercase aliases used by several cognitive service modules
KAFKA_BOOTSTRAP_SERVERS = _INFRA_KAFKA_BOOTSTRAP_SERVERS
TOPIC_NEXT_EVENT = SOMABRAIN_TOPIC_NEXT_EVENT
TOPIC_GLOBAL_FRAME = SOMABRAIN_TOPIC_GLOBAL_FRAME
TOPIC_STATE_UPDATES = SOMABRAIN_TOPIC_STATE_UPDATES
TOPIC_AGENT_UPDATES = SOMABRAIN_TOPIC_AGENT_UPDATES
TOPIC_ACTION_UPDATES = SOMABRAIN_TOPIC_ACTION_UPDATES
topic_config_updates = SOMABRAIN_TOPIC_CONFIG_UPDATES
TOPIC_SEGMENTS = SOMABRAIN_TOPIC_SEGMENTS

# --- LEARNER SETTINGS ---
SOMABRAIN_LEARNING_TENANTS_FILE = env.str(
    "SOMABRAIN_LEARNING_TENANTS_FILE", default="/app/config/learning.tenants.yaml"
)

# --- SEGMENTATION SETTINGS ---
ENABLE_COG_THREADS = env.bool("ENABLE_COG_THREADS", default=True)
SEGMENTATION_HEALTH_PORT = env.int("SEGMENTATION_HEALTH_PORT", default=9016)
SEGMENT_HEALTH_PORT = SEGMENTATION_HEALTH_PORT
SEGMENT_HEALTH_ENABLE = env.str("SEGMENTATION_HEALTH_ENABLE", default="1")
SEGMENT_GRAD_THRESHOLD = env.float("SOMABRAIN_SEGMENT_GRAD_THRESHOLD", default=0.2)
SEGMENT_HMM_ENABLED = env.bool("SOMABRAIN_SEGMENT_HMM_ENABLED", default=True)
SEGMENT_HMM_THRESHOLD = env.float("SOMABRAIN_SEGMENT_HMM_THRESHOLD", default=0.6)

# --- MEMORY SETTINGS ---
# Memory HTTP service
SOMABRAIN_MEMORY_HTTP_HOST = env.str(
    "SOMABRAIN_MEMORY_HTTP_HOST", default=env.str("MEMORY_HTTP_HOST", default=None)
)
SOMABRAIN_MEMORY_HTTP_PORT = env.int(
    "SOMABRAIN_MEMORY_HTTP_PORT", default=env.int("MEMORY_HTTP_PORT", default=0)
)
SOMABRAIN_MEMORY_HTTP_SCHEME = env.str(
    "SOMABRAIN_MEMORY_HTTP_SCHEME",
    default=env.str("MEMORY_HTTP_SCHEME", default="http"),
)
SOMABRAIN_MEMORY_HTTP_ENDPOINT = env.str(
    "SOMABRAIN_MEMORY_HTTP_ENDPOINT",
    default=env.str("MEMORY_SERVICE_URL", default=_INFRA_MEMORY_HTTP_ENDPOINT),
)
# SOMABRAIN_MEMORY_HTTP_TOKEN is defined once, in settings/infra.py (Vault ->
# module state). Import and reuse that value here so the two modules cannot
# drift. A missing token is a refusal, never "": an empty string dressed up as
# a default is a shim that lets a service authenticate as nobody (Rule 91).
if not SOMABRAIN_MEMORY_HTTP_TOKEN:
    raise environ.ImproperlyConfigured(
        "SOMABRAIN_MEMORY_HTTP_TOKEN must be provisioned via Vault "
        "(settings/infra.py). An empty memory HTTP token is a refusal, "
        "never a default."
    )
# Secret: Vault only (somabrain/runtime[provenance_secret]). No ENV, no default.
SOMABRAIN_PROVENANCE_SECRET = _resolved("SOMABRAIN_PROVENANCE_SECRET")
SOMABRAIN_MEMORY_MAX = env.str("SOMABRAIN_MEMORY_MAX", default="10GB")
MEMORY_DB_PATH = env.str("MEMORY_DB_PATH", default="./data/memory.db")

# Memory Backend Mode Selection
SOMABRAIN_MEMORY_MODE = env.str("SOMABRAIN_MEMORY_MODE", default="http")
if SOMABRAIN_MEMORY_MODE not in ("http", "direct"):
    raise ValueError(
        f"Invalid SOMABRAIN_MEMORY_MODE: {SOMABRAIN_MEMORY_MODE}. "
        "Must be 'http' or 'direct'."
    )
SOMABRAIN_MEMORY_ENABLE_WEIGHTING = env.bool(
    "SOMABRAIN_FF_MEMORY_WEIGHTING",
    default=env.bool("SOMABRAIN_MEMORY_ENABLE_WEIGHTING", default=False),
)
SOMABRAIN_MEMORY_PHASE_PRIORS = env.str("SOMABRAIN_MEMORY_PHASE_PRIORS", default="")
SOMABRAIN_MEMORY_QUALITY_EXP = env.float("SOMABRAIN_MEMORY_QUALITY_EXP", default=1.0)
SOMABRAIN_MEMORY_FAST_ACK = env.bool("SOMABRAIN_MEMORY_FAST_ACK", default=False)

# Memory degradation
SOMABRAIN_MEMORY_DEGRADE_QUEUE = env.bool(
    "SOMABRAIN_MEMORY_DEGRADE_QUEUE", default=True
)
SOMABRAIN_MEMORY_DEGRADE_READONLY = env.bool(
    "SOMABRAIN_MEMORY_DEGRADE_READONLY", default=False
)
SOMABRAIN_MEMORY_DEGRADE_TOPIC = env.str(
    "SOMABRAIN_MEMORY_DEGRADE_TOPIC", default="memory.degraded"
)
SOMABRAIN_MEMORY_HEALTH_POLL_INTERVAL = env.float(
    "SOMABRAIN_MEMORY_HEALTH_POLL_INTERVAL", default=5.0
)
SOMABRAIN_DEBUG_MEMORY_CLIENT = env.bool("SOMABRAIN_DEBUG_MEMORY_CLIENT", default=False)

# Working memory configuration
# Seam dim unity (ARCHITECTURE-INVARIANTS §2):
# MEM_EMBED_DIM (agent) == SOMABRAIN_EMBED_DIM == SOMA_VECTOR_DIM (SFM).
# Configuration-owned and auditable via system health — never hardcoded in logic.
SOMABRAIN_EMBED_DIM = env.int("EMBED_DIM", default=768)
# Certified seam contract the effective dim must match (fail-closed on mismatch).
SOMABRAIN_EMBED_DIM_SEAM = env.int("EMBED_DIM_SEAM", default=768)
SOMABRAIN_WM_SIZE = env.int("SOMABRAIN_WM_SIZE", default=64)
# Single recency time scale (seconds) for the stretched-exponential kernel.
# WM, recall ranking, unified scorer, and context decay all use this key.
SOMABRAIN_WM_RECENCY_TIME_SCALE = env.float(
    "SOMABRAIN_WM_RECENCY_TIME_SCALE", default=60.0
)
SOMABRAIN_WM_RECENCY_MAX_STEPS = env.int("SOMABRAIN_WM_RECENCY_MAX_STEPS", default=1000)
SOMABRAIN_WM_ALPHA = env.float("SOMABRAIN_WM_ALPHA", default=0.6)
SOMABRAIN_WM_BETA = env.float("SOMABRAIN_WM_BETA", default=0.3)
SOMABRAIN_WM_GAMMA = env.float("SOMABRAIN_WM_GAMMA", default=0.1)
SOMABRAIN_WM_SALIENCE_THRESHOLD = env.float(
    "SOMABRAIN_WM_SALIENCE_THRESHOLD", default=0.4
)
SOMABRAIN_WM_PER_COL_MIN_CAPACITY = env.int(
    "SOMABRAIN_WM_PER_COL_MIN_CAPACITY", default=16
)
SOMABRAIN_WM_VOTE_SOFTMAX_FLOOR = env.float(
    "SOMABRAIN_WM_VOTE_SOFTMAX_FLOOR", default=1e-4
)
SOMABRAIN_WM_VOTE_ENTROPY_EPS = env.float("SOMABRAIN_WM_VOTE_ENTROPY_EPS", default=1e-9)
SOMABRAIN_WM_PER_TENANT_CAPACITY = env.int(
    "SOMABRAIN_WM_PER_TENANT_CAPACITY", default=128
)
SOMABRAIN_MTWM_MAX_TENANTS = env.int("SOMABRAIN_MTWM_MAX_TENANTS", default=1000)

# Micro-circuit configuration
SOMABRAIN_MICRO_CIRCUITS = env.int("SOMABRAIN_MICRO_CIRCUITS", default=1)
SOMABRAIN_MICRO_VOTE_TEMPERATURE = env.float(
    "SOMABRAIN_MICRO_VOTE_TEMPERATURE", default=0.25
)
SOMABRAIN_USE_MICROCIRCUITS = env.bool("SOMABRAIN_USE_MICROCIRCUITS", default=False)
SOMABRAIN_MICRO_MAX_TENANTS = env.int("SOMABRAIN_MICRO_MAX_TENANTS", default=1000)

# Tiered memory cleanup
SOMABRAIN_CLEANUP_BACKEND = env.str("SOMABRAIN_CLEANUP_BACKEND", default="milvus")
SOMABRAIN_CLEANUP_TOPK = env.int("SOMABRAIN_CLEANUP_TOPK", default=64)
SOMABRAIN_CLEANUP_HNSW_M = env.int("SOMABRAIN_CLEANUP_HNSW_M", default=32)
SOMABRAIN_CLEANUP_HNSW_EF_CONSTRUCTION = env.int(
    "SOMABRAIN_CLEANUP_HNSW_EF_CONSTRUCTION", default=200
)
SOMABRAIN_CLEANUP_HNSW_EF_SEARCH = env.int(
    "SOMABRAIN_CLEANUP_HNSW_EF_SEARCH", default=128
)

# Scorer weights
SOMABRAIN_SCORER_W_COSINE = env.float("SOMABRAIN_SCORER_W_COSINE", default=0.6)
SOMABRAIN_SCORER_W_FD = env.float("SOMABRAIN_SCORER_W_FD", default=0.25)
SOMABRAIN_SCORER_W_RECENCY = env.float("SOMABRAIN_SCORER_W_RECENCY", default=0.15)
SOMABRAIN_SCORER_WEIGHT_MIN = env.float("SOMABRAIN_SCORER_WEIGHT_MIN", default=0.0)
SOMABRAIN_SCORER_WEIGHT_MAX = env.float("SOMABRAIN_SCORER_WEIGHT_MAX", default=1.0)

# Retrieval weights
SOMABRAIN_RETRIEVAL_ALPHA = env.float("SOMABRAIN_RETRIEVAL_ALPHA", default=1.0)
SOMABRAIN_RETRIEVAL_BETA = env.float("SOMABRAIN_RETRIEVAL_BETA", default=0.2)
SOMABRAIN_RETRIEVAL_GAMMA = env.float("SOMABRAIN_RETRIEVAL_GAMMA", default=0.1)
SOMABRAIN_RETRIEVAL_TAU = env.float("SOMABRAIN_RETRIEVAL_TAU", default=0.7)
# Kernel shape for the single recency family (scale is SOMABRAIN_WM_RECENCY_TIME_SCALE).
SOMABRAIN_RECENCY_SHARPNESS = env.float("SOMABRAIN_RECENCY_SHARPNESS", default=1.2)
SOMABRAIN_RECENCY_FLOOR = env.float("SOMABRAIN_RECENCY_FLOOR", default=0.05)
SOMABRAIN_DENSITY_TARGET = env.float("SOMABRAIN_DENSITY_TARGET", default=0.2)
SOMABRAIN_DENSITY_FLOOR = env.float("SOMABRAIN_DENSITY_FLOOR", default=0.6)
SOMABRAIN_DENSITY_WEIGHT = env.float("SOMABRAIN_DENSITY_WEIGHT", default=0.35)
SOMABRAIN_TAU_MIN = env.float("SOMABRAIN_TAU_MIN", default=0.4)
SOMABRAIN_TAU_MAX = env.float("SOMABRAIN_TAU_MAX", default=1.2)
SOMABRAIN_TAU_INC_UP = env.float("SOMABRAIN_TAU_INC_UP", default=0.1)
SOMABRAIN_TAU_INC_DOWN = env.float("SOMABRAIN_TAU_INC_DOWN", default=0.05)
SOMABRAIN_DUP_RATIO_THRESHOLD = env.float("SOMABRAIN_DUP_RATIO_THRESHOLD", default=0.5)

# Recall behavior
SOMABRAIN_RECALL_FULL_POWER = env.bool("SOMABRAIN_RECALL_FULL_POWER", default=True)
SOMABRAIN_RECALL_SIMPLE_DEFAULTS = env.bool(
    "SOMABRAIN_RECALL_SIMPLE_DEFAULTS", default=False
)
SOMABRAIN_RECALL_DEFAULT_RERANK = env.str(
    "SOMABRAIN_RECALL_DEFAULT_RERANK", default="auto"
)
SOMABRAIN_RECALL_DEFAULT_PERSIST = env.bool(
    "SOMABRAIN_RECALL_DEFAULT_PERSIST", default=True
)
SOMABRAIN_RECALL_DEFAULT_RETRIEVERS = env.str(
    "SOMABRAIN_RECALL_DEFAULT_RETRIEVERS", default="vector,wm,graph,lexical"
)

# Salience configuration
SOMABRAIN_SALIENCE_METHOD = env.str("SOMABRAIN_SALIENCE_METHOD", default="dense")
SOMABRAIN_SALIENCE_FD_RANK = env.int("SOMABRAIN_SALIENCE_FD_RANK", default=128)
SOMABRAIN_SALIENCE_FD_DECAY = env.float("SOMABRAIN_SALIENCE_FD_DECAY", default=0.9)
SOMABRAIN_SALIENCE_W_NOVELTY = env.float("SOMABRAIN_SALIENCE_W_NOVELTY", default=0.6)
SOMABRAIN_SALIENCE_W_ERROR = env.float("SOMABRAIN_SALIENCE_W_ERROR", default=0.4)
SOMABRAIN_SALIENCE_THRESHOLD_STORE = env.float(
    "SOMABRAIN_SALIENCE_THRESHOLD_STORE", default=0.5
)
SOMABRAIN_SALIENCE_THRESHOLD_ACT = env.float(
    "SOMABRAIN_SALIENCE_THRESHOLD_ACT", default=0.7
)
SOMABRAIN_SALIENCE_HYSTERESIS = env.float("SOMABRAIN_SALIENCE_HYSTERESIS", default=0.1)
SOMABRAIN_SALIENCE_FD_WEIGHT = env.float("SOMABRAIN_SALIENCE_FD_WEIGHT", default=0.25)
SOMABRAIN_SALIENCE_FD_ENERGY_FLOOR = env.float(
    "SOMABRAIN_SALIENCE_FD_ENERGY_FLOOR", default=0.9
)
SOMABRAIN_SALIENCE_SOFT_TEMPERATURE = env.float(
    "SOMABRAIN_SALIENCE_SOFT_TEMPERATURE", default=0.1
)
SOMABRAIN_USE_SOFT_SALIENCE = env.bool("SOMABRAIN_USE_SOFT_SALIENCE", default=False)

# Feature toggles
SOMABRAIN_USE_HRR = env.bool("SOMABRAIN_USE_HRR", default=False)
SOMABRAIN_USE_META_BRAIN = env.bool("SOMABRAIN_USE_META_BRAIN", default=False)
SOMABRAIN_USE_EXEC_CONTROLLER = env.bool("SOMABRAIN_USE_EXEC_CONTROLLER", default=False)
SOMABRAIN_USE_DRIFT_MONITOR = env.bool("SOMABRAIN_USE_DRIFT_MONITOR", default=False)
SOMABRAIN_USE_SDR_PREFILTER = env.bool("SOMABRAIN_USE_SDR_PREFILTER", default=False)
SOMABRAIN_USE_GRAPH_AUGMENT = env.bool("SOMABRAIN_USE_GRAPH_AUGMENT", default=False)
SOMABRAIN_USE_HRR_FIRST = env.bool("SOMABRAIN_USE_HRR_FIRST", default=False)

# Graph configuration
SOMABRAIN_GRAPH_HOPS = env.int("SOMABRAIN_GRAPH_HOPS", default=2)
SOMABRAIN_GRAPH_LIMIT = env.int("SOMABRAIN_GRAPH_LIMIT", default=20)
SOMABRAIN_GRAPH_FILE = env.str("SOMABRAIN_GRAPH_FILE", default=None)
SOMABRAIN_GRAPH_FILE_ACTION = env.str("SOMABRAIN_GRAPH_FILE_ACTION", default=None)
SOMABRAIN_GRAPH_FILE_AGENT = env.str("SOMABRAIN_GRAPH_FILE_AGENT", default=None)
SOMABRAIN_GRAPH_FILE_STATE = env.str("SOMABRAIN_GRAPH_FILE_STATE", default=None)

# Planner / graph walk
SOMABRAIN_PLANNER_LENGTH_PENALTY_SCALE = env.float(
    "SOMABRAIN_PLANNER_LENGTH_PENALTY_SCALE", default=1024.0
)
SOMABRAIN_PLANNER_MEMORY_PENALTY_SCALE = env.float(
    "SOMABRAIN_PLANNER_MEMORY_PENALTY_SCALE", default=10.0
)
SOMABRAIN_PLANNER_RWR_STEPS = env.int("SOMABRAIN_PLANNER_RWR_STEPS", default=20)
SOMABRAIN_PLANNER_RWR_RESTART = env.float("SOMABRAIN_PLANNER_RWR_RESTART", default=0.15)
SOMABRAIN_PLANNER_RWR_MAX_NODES = env.int(
    "SOMABRAIN_PLANNER_RWR_MAX_NODES", default=128
)
SOMABRAIN_PLANNER_RWR_EDGES_PER_NODE = env.int(
    "SOMABRAIN_PLANNER_RWR_EDGES_PER_NODE", default=32
)
SOMABRAIN_PLANNER_RWR_MAX_ITEMS = env.int("SOMABRAIN_PLANNER_RWR_MAX_ITEMS", default=5)

# --- COGNITIVE SETTINGS ---
# HRR configuration
SOMABRAIN_HRR_DIM = env.int("SOMABRAIN_HRR_DIM", default=8192)
SOMABRAIN_HRR_DTYPE = env.str("SOMABRAIN_HRR_DTYPE", default="float32")
SOMABRAIN_HRR_RENORM = env.bool("SOMABRAIN_HRR_RENORM", default=True)
SOMABRAIN_HRR_VECTOR_FAMILY = env.str("SOMABRAIN_HRR_VECTOR_FAMILY", default="bhdc")
SOMABRAIN_BHDC_SPARSITY = env.float("SOMABRAIN_BHDC_SPARSITY", default=0.1)

# SDR configuration
SOMABRAIN_SDR_BITS = env.int("SOMABRAIN_SDR_BITS", default=2048)
SOMABRAIN_SDR_DENSITY = env.float("SOMABRAIN_SDR_DENSITY", default=0.03)
SOMABRAIN_SDR_DIM = env.int("SOMABRAIN_SDR_DIM", default=16384)
SOMABRAIN_SDR_SPARSITY = env.float("SOMABRAIN_SDR_SPARSITY", default=0.01)

# Context configuration
SOMABRAIN_CONTEXT_BUDGET_TOKENS = env.int(
    "SOMABRAIN_CONTEXT_BUDGET_TOKENS", default=2048
)
SOMABRAIN_MAX_SUPERPOSE = env.int("SOMABRAIN_MAX_SUPERPOSE", default=32)
SOMABRAIN_DEFAULT_WM_SLOTS = env.int("SOMABRAIN_DEFAULT_WM_SLOTS", default=12)

# Determinism and seeding
SOMABRAIN_GLOBAL_SEED = env.int("SOMABRAIN_GLOBAL_SEED", default=42)
SOMABRAIN_DETERMINISM = env.bool("SOMABRAIN_DETERMINISM", default=True)

# Quotas
SOMABRAIN_QUOTA_TENANT = env.int("SOMABRAIN_QUOTA_TENANT", default=10000)
SOMABRAIN_QUOTA_TOOL = env.int("SOMABRAIN_QUOTA_TOOL", default=1000)
SOMABRAIN_QUOTA_ACTION = env.int("SOMABRAIN_QUOTA_ACTION", default=500)

# Quantum layer
SOMABRAIN_QUANTUM_DIM = env.int("SOMABRAIN_QUANTUM_DIM", default=2048)
SOMABRAIN_QUANTUM_SPARSITY = env.float("SOMABRAIN_QUANTUM_SPARSITY", default=0.1)

# Planning configuration
SOMABRAIN_USE_PLANNER = env.bool("SOMABRAIN_USE_PLANNER", default=False)
SOMABRAIN_USE_FOCUS_STATE = env.bool("SOMABRAIN_USE_FOCUS_STATE", default=True)
SOMABRAIN_PLAN_MAX_STEPS = env.int("SOMABRAIN_PLAN_MAX_STEPS", default=5)
SOMABRAIN_PLANNER_BACKEND = env.str("SOMABRAIN_PLANNER_BACKEND", default="bfs")

# Sleep system
SOMABRAIN_ENABLE_SLEEP = env.bool("SOMABRAIN_ENABLE_SLEEP", default=True)
SOMABRAIN_CONSOLIDATION_ENABLED = env.bool(
    "SOMABRAIN_CONSOLIDATION_ENABLED", default=True
)
SOMABRAIN_SLEEP_INTERVAL_SECONDS = env.int(
    "SOMABRAIN_SLEEP_INTERVAL_SECONDS", default=3600
)
SOMABRAIN_CONSOLIDATION_TIMEOUT_S = env.float(
    "SOMABRAIN_CONSOLIDATION_TIMEOUT_S", default=30.0
)
SOMABRAIN_NREM_BATCH_SIZE = env.int("SOMABRAIN_NREM_BATCH_SIZE", default=16)
SOMABRAIN_MAX_SUMMARIES_PER_CYCLE = env.int(
    "SOMABRAIN_MAX_SUMMARIES_PER_CYCLE", default=3
)
SOMABRAIN_REM_RECOMB_RATE = env.float("SOMABRAIN_REM_RECOMB_RATE", default=0.2)
SLEEP_K0 = env.int("SLEEP_K0", default=10)
SLEEP_T0 = env.float("SLEEP_T0", default=1.0)
SLEEP_TAU0 = env.float("SLEEP_TAU0", default=0.1)
SLEEP_ETA0 = env.float("SLEEP_ETA0", default=0.01)
SLEEP_LAMBDA0 = env.float("SLEEP_LAMBDA0", default=0.5)
SLEEP_B0 = env.float("SLEEP_B0", default=1.0)
SLEEP_K_MIN = env.int("SLEEP_K_MIN", default=5)
SLEEP_T_MIN = env.float("SLEEP_T_MIN", default=0.5)
SLEEP_ALPHA_K = env.float("SLEEP_ALPHA_K", default=0.1)
SLEEP_ALPHA_T = env.float("SLEEP_ALPHA_T", default=0.05)
SLEEP_ALPHA_TAU = env.float("SLEEP_ALPHA_TAU", default=0.05)
SLEEP_ALPHA_ETA = env.float("SLEEP_ALPHA_ETA", default=0.01)
SLEEP_BETA_B = env.float("SLEEP_BETA_B", default=0.1)

# Rate limiting
SOMABRAIN_RATE_RPS = env.int("SOMABRAIN_RATE_RPS", default=1000)
SOMABRAIN_RATE_BURST = env.int("SOMABRAIN_RATE_BURST", default=2000)
SOMABRAIN_WRITE_DAILY_LIMIT = env.int("SOMABRAIN_WRITE_DAILY_LIMIT", default=100000)

# Learning & Adaptation Settings
SOMABRAIN_TAU_DECAY_ENABLED = env.bool("SOMABRAIN_TAU_DECAY_ENABLED", default=False)
SOMABRAIN_TAU_DECAY_RATE = env.float("SOMABRAIN_TAU_DECAY_RATE", default=0.0)
SOMABRAIN_TAU_ANNEAL_MODE = env.str("SOMABRAIN_TAU_ANNEAL_MODE", default=None)
SOMABRAIN_TAU_ANNEAL_RATE = env.float("SOMABRAIN_TAU_ANNEAL_RATE", default=0.0)
SOMABRAIN_TAU_ANNEAL_STEP_INTERVAL = env.int(
    "SOMABRAIN_TAU_ANNEAL_STEP_INTERVAL", default=0
)
SOMABRAIN_ENTROPY_CAP_ENABLED = env.bool("SOMABRAIN_ENTROPY_CAP_ENABLED", default=False)
SOMABRAIN_ENTROPY_CAP = env.float("SOMABRAIN_ENTROPY_CAP", default=0.0)
SOMABRAIN_LEARNING_RATE_DYNAMIC = env.bool(
    "SOMABRAIN_LEARNING_RATE_DYNAMIC", default=False
)

SOMABRAIN_UTILITY_LAMBDA = env.float("SOMABRAIN_UTILITY_LAMBDA", default=1.0)
SOMABRAIN_UTILITY_MU = env.float("SOMABRAIN_UTILITY_MU", default=0.1)
SOMABRAIN_UTILITY_NU = env.float("SOMABRAIN_UTILITY_NU", default=0.05)
# Emotion decay rate (fraction of distance to neutral per decay step).
SOMABRAIN_EMOTION_DECAY_RATE = env.float("SOMABRAIN_EMOTION_DECAY_RATE", default=0.0)
SOMABRAIN_ADAPTATION_GAIN_ALPHA = env.float(
    "SOMABRAIN_ADAPTATION_GAIN_ALPHA", default=1.0
)
SOMABRAIN_ADAPTATION_GAIN_GAMMA = env.float(
    "SOMABRAIN_ADAPTATION_GAIN_GAMMA", default=-0.5
)
SOMABRAIN_ADAPTATION_GAIN_LAMBDA = env.float(
    "SOMABRAIN_ADAPTATION_GAIN_LAMBDA", default=1.0
)
SOMABRAIN_ADAPTATION_GAIN_MU = env.float("SOMABRAIN_ADAPTATION_GAIN_MU", default=-0.25)
SOMABRAIN_ADAPTATION_GAIN_NU = env.float("SOMABRAIN_ADAPTATION_GAIN_NU", default=-0.25)

SOMABRAIN_ADAPTATION_ALPHA_MIN = env.float(
    "SOMABRAIN_ADAPTATION_ALPHA_MIN", default=0.1
)
SOMABRAIN_ADAPTATION_ALPHA_MAX = env.float(
    "SOMABRAIN_ADAPTATION_ALPHA_MAX", default=5.0
)
SOMABRAIN_ADAPTATION_GAMMA_MIN = env.float(
    "SOMABRAIN_ADAPTATION_GAMMA_MIN", default=0.0
)
SOMABRAIN_ADAPTATION_GAMMA_MAX = env.float(
    "SOMABRAIN_ADAPTATION_GAMMA_MAX", default=1.0
)
SOMABRAIN_ADAPTATION_LAMBDA_MIN = env.float(
    "SOMABRAIN_ADAPTATION_LAMBDA_MIN", default=0.1
)
SOMABRAIN_ADAPTATION_LAMBDA_MAX = env.float(
    "SOMABRAIN_ADAPTATION_LAMBDA_MAX", default=5.0
)
SOMABRAIN_ADAPTATION_MU_MIN = env.float("SOMABRAIN_ADAPTATION_MU_MIN", default=0.01)
SOMABRAIN_ADAPTATION_MU_MAX = env.float("SOMABRAIN_ADAPTATION_MU_MAX", default=5.0)
SOMABRAIN_ADAPTATION_NU_MIN = env.float("SOMABRAIN_ADAPTATION_NU_MIN", default=0.01)
SOMABRAIN_ADAPTATION_NU_MAX = env.float("SOMABRAIN_ADAPTATION_NU_MAX", default=5.0)

# Predictor configuration
SOMABRAIN_PREDICTOR_PROVIDER = env.str("SOMABRAIN_PREDICTOR_PROVIDER", default="mahal")
SOMABRAIN_MEMORY_FAST_ACK = env.bool("SOMABRAIN_MEMORY_FAST_ACK", default=False)
SOMABRAIN_PREDICTOR_DIM = env.int("SOMABRAIN_PREDICTOR_DIM", default=16)
SOMABRAIN_PREDICTOR_ALPHA = env.float("SOMABRAIN_PREDICTOR_ALPHA", default=2.0)
SOMABRAIN_PREDICTOR_GAMMA = env.float("SOMABRAIN_PREDICTOR_GAMMA", default=-0.5)

# Learner dead-letter queue
SOMABRAIN_LEARNER_DLQ_PATH = env.str(
    "SOMABRAIN_LEARNER_DLQ_PATH", default="./data/learner_dlq.jsonl"
)
SOMABRAIN_LEARNER_DLQ_TOPIC = env.str(
    "SOMABRAIN_LEARNER_DLQ_TOPIC", default="cog.learner.dlq"
)

# LLM endpoint
SOMABRAIN_LLM_ENDPOINT = env.str("SOMABRAIN_LLM_ENDPOINT", default=None)

# --- OAK (ROAMDP) SETTINGS ---
ENABLE_OAK = env.bool("ENABLE_OAK", default=False)
OAK_BASE_UTILITY = env.float("OAK_BASE_UTILITY", default=1.0)
OAK_UTILITY_FACTOR = env.float("OAK_UTILITY_FACTOR", default=0.1)
OAK_TAU_MIN = env.float("OAK_TAU_MIN", default=30.0)
OAK_TAU_MAX = env.float("OAK_TAU_MAX", default=300.0)
OAK_PLAN_MAX_OPTIONS = env.int("OAK_PLAN_MAX_OPTIONS", default=10)
OAK_SIMILARITY_THRESHOLD = env.float("OAK_SIMILARITY_THRESHOLD", default=0.8)
OAK_REWARD_THRESHOLD = env.float("OAK_REWARD_THRESHOLD", default=0.5)
OAK_NOVELTY_THRESHOLD = env.float("OAK_NOVELTY_THRESHOLD", default=0.2)
OAK_GAMMA = env.float("OAK_GAMMA", default=0.99)
OAK_ALPHA = env.float("OAK_ALPHA", default=0.1)
OAK_KAPPA = env.float("OAK_KAPPA", default=1.0)

# ============================================================================
# ADMINISTRABLE KNOBS — declared once (schema default lives HERE only).
# Call sites read these through somabrain.settings.resolve.optional_setting /
# require_setting. There is no call-site default: the number appears once.
# (R-VAL-01: declared exactly once; promoted from former call-site literals.)
# ============================================================================
CALIBRATION_ENABLED = env.bool("CALIBRATION_ENABLED", default=False)
HEALTH_PING_TIMEOUT = env.float("HEALTH_PING_TIMEOUT", default=0.5)
HRR_DIM = env.int("HRR_DIM", default=512)
KAFKA_BOOTSTRAP = env.str("KAFKA_BOOTSTRAP", default="")
KEYCLOAK_REALM = env.str("KEYCLOAK_REALM", default="unknown")
MEMORY_HEALTH_POLL_INTERVAL = env.float("MEMORY_HEALTH_POLL_INTERVAL", default=5.0)
OAK_OPTION_MODEL_MANAGED = env.bool("OAK_OPTION_MODEL_MANAGED", default=False)
OUTBOX_BACKPRESSURE_ENABLED = env.str("OUTBOX_BACKPRESSURE_ENABLED", default="true")
OUTBOX_TENANT_BATCH_LIMIT = env.int("OUTBOX_TENANT_BATCH_LIMIT", default=50)
PLAN_MAX_STEPS = env.int("PLAN_MAX_STEPS", default=5)
PLAN_TIME_BUDGET_MS = env.int("PLAN_TIME_BUDGET_MS", default=50)
REQUIRE_OPA = env.bool("REQUIRE_OPA", default=False)
SLEEP_MAX_SECONDS = env.int("SLEEP_MAX_SECONDS", default=3600)
SOMABRAIN_AUDIT_TOPIC = env.str("SOMABRAIN_AUDIT_TOPIC", default="soma.audit")
SOMABRAIN_BLOCK_UA_REGEX = env.str("SOMABRAIN_BLOCK_UA_REGEX", default="")
SOMABRAIN_CHEB_K = env.int("SOMABRAIN_CHEB_K", default=30)
SOMABRAIN_CONF_ALPHA = env.float("SOMABRAIN_CONF_ALPHA", default=2.0)
SOMABRAIN_CONSTITUTION_SIGNER_ID = env.str("SOMABRAIN_CONSTITUTION_SIGNER_ID", default="default")
SOMABRAIN_CONSTITUTION_THRESHOLD = env.int("SOMABRAIN_CONSTITUTION_THRESHOLD", default=1)
SOMABRAIN_DEFAULT_NOVELTY = env.float("SOMABRAIN_DEFAULT_NOVELTY", default=0.0)
SOMABRAIN_DEFAULT_SALIENCE = env.float("SOMABRAIN_DEFAULT_SALIENCE", default=0.0)
SOMABRAIN_DEGRADATION_KAFKA_TOPIC = env.str("SOMABRAIN_DEGRADATION_KAFKA_TOPIC", default="")
SOMABRAIN_DIFFUSION_T = env.float("SOMABRAIN_DIFFUSION_T", default=0.5)
SOMABRAIN_DRIFT_STORE_PATH = env.str("SOMABRAIN_DRIFT_STORE_PATH", default="")
SOMABRAIN_DRIFT_THRESHOLD = env.float("SOMABRAIN_DRIFT_THRESHOLD", default=0.3)
SOMABRAIN_DRIFT_WINDOW = env.int("SOMABRAIN_DRIFT_WINDOW", default=256)
SOMABRAIN_EXEC_BANDIT_EPS = env.float("SOMABRAIN_EXEC_BANDIT_EPS", default=0.1)
SOMABRAIN_EXEC_EXPLORE_BOOST_K = env.float("SOMABRAIN_EXEC_EXPLORE_BOOST_K", default=1.2)
SOMABRAIN_EXEC_USE_BANDITS = env.bool("SOMABRAIN_EXEC_USE_BANDITS", default=False)
SOMABRAIN_EXEC_WINDOW = env.int("SOMABRAIN_EXEC_WINDOW", default=64)
SOMABRAIN_HRR_ANCHORS_MAX = env.int("SOMABRAIN_HRR_ANCHORS_MAX", default=256)
SOMABRAIN_HRR_DECAY_LAMBDA = env.float("SOMABRAIN_HRR_DECAY_LAMBDA", default=0.05)
SOMABRAIN_HRR_SEED = env.int("SOMABRAIN_HRR_SEED", default=42)
SOMABRAIN_INTEGRATOR_ENTROPY_CAP = env.float("SOMABRAIN_INTEGRATOR_ENTROPY_CAP", default=0.0)
SOMABRAIN_KILL_SWITCH = env.bool("SOMABRAIN_KILL_SWITCH", default=False)
SOMABRAIN_LANCZOS_M = env.int("SOMABRAIN_LANCZOS_M", default=20)
SOMABRAIN_LOG_TASK_TRUNCATE_LEN = env.int("SOMABRAIN_LOG_TASK_TRUNCATE_LEN", default=50)
SOMABRAIN_MATH_BHDC_BINARY_MODE = env.bool("SOMABRAIN_MATH_BHDC_BINARY_MODE", default=False)
SOMABRAIN_MATH_BHDC_MIX = env.float("SOMABRAIN_MATH_BHDC_MIX", default=0.5)
SOMABRAIN_MATH_BHDC_SPARSITY = env.float("SOMABRAIN_MATH_BHDC_SPARSITY", default=0.1)
SOMABRAIN_MATH_BINDING_SEED = env.int("SOMABRAIN_MATH_BINDING_SEED", default=42)
SOMABRAIN_META_GAIN = env.float("SOMABRAIN_META_GAIN", default=0.1)
SOMABRAIN_META_LIMIT = env.float("SOMABRAIN_META_LIMIT", default=1.0)
SOMABRAIN_MILVUS_CONNECT_TIMEOUT = env.int("SOMABRAIN_MILVUS_CONNECT_TIMEOUT", default=5)
SOMABRAIN_MILVUS_LATENCY_WINDOW = env.int("SOMABRAIN_MILVUS_LATENCY_WINDOW", default=50)
SOMABRAIN_MILVUS_RECONCILE_INTERVAL = env.float("SOMABRAIN_MILVUS_RECONCILE_INTERVAL", default=3600.0)
SOMABRAIN_MILVUS_SECURE = env.bool("SOMABRAIN_MILVUS_SECURE", default=False)
SOMABRAIN_MILVUS_SEGMENT_REFRESH_INTERVAL = env.float("SOMABRAIN_MILVUS_SEGMENT_REFRESH_INTERVAL", default=60.0)
SOMABRAIN_MILVUS_UPSERT_BACKOFF_BASE = env.float("SOMABRAIN_MILVUS_UPSERT_BACKOFF_BASE", default=0.5)
SOMABRAIN_MILVUS_UPSERT_RETRIES = env.int("SOMABRAIN_MILVUS_UPSERT_RETRIES", default=3)
SOMABRAIN_OUTBOX_SYNC_INTERVAL = env.float("SOMABRAIN_OUTBOX_SYNC_INTERVAL", default=10.0)
SOMABRAIN_PLAN_TIME_BUDGET_MS = env.int("SOMABRAIN_PLAN_TIME_BUDGET_MS", default=50)
SOMABRAIN_PREDICTOR_TIMEOUT_MS = env.int("SOMABRAIN_PREDICTOR_TIMEOUT_MS", default=1000)
SOMABRAIN_PROVENANCE_STRICT_DENY = env.bool("SOMABRAIN_PROVENANCE_STRICT_DENY", default=False)
SOMABRAIN_REQUIRE_PROVENANCE = env.bool("SOMABRAIN_REQUIRE_PROVENANCE", default=False)
SOMABRAIN_SLOW_PREDICTOR_DELAY_MS = env.int("SOMABRAIN_SLOW_PREDICTOR_DELAY_MS", default=1000)
USE_MICROCIRCUITS = env.bool("USE_MICROCIRCUITS", default=False)
USE_PLANNER = env.bool("USE_PLANNER", default=False)
ALLOW_TINY_EMBEDDER = env.bool("ALLOW_TINY_EMBEDDER", default=False)
CHEBYSHEV_K = env.int("CHEBYSHEV_K", default=30)
CONSUMER_GROUP = env.str("CONSUMER_GROUP", default="wm-updates-cache")
DIFFUSION_T = env.float("DIFFUSION_T", default=0.5)
ENABLE_LEARNING_STATE_PERSISTENCE = env.str("ENABLE_LEARNING_STATE_PERSISTENCE", default="")
FEEDBACK_RATE_LIMIT_PER_MINUTE = env.int("FEEDBACK_RATE_LIMIT_PER_MINUTE", default=0)
HEAT_METHOD = env.str("HEAT_METHOD", default="chebyshev")
HTTP_KEEPALIVE_CONNECTIONS = env.str("HTTP_KEEPALIVE_CONNECTIONS", default="default_keepalive")
HTTP_MAX_CONNECTIONS = env.str("HTTP_MAX_CONNECTIONS", default="default_max")
HTTP_RETRIES = env.str("HTTP_RETRIES", default="default_retries")
JOURNAL_COMPRESSION = env.bool("JOURNAL_COMPRESSION", default=True)
JOURNAL_MAX_FILES = env.int("JOURNAL_MAX_FILES", default=10)
JOURNAL_RETENTION_DAYS = env.int("JOURNAL_RETENTION_DAYS", default=7)
JOURNAL_ROTATION_INTERVAL = env.int("JOURNAL_ROTATION_INTERVAL", default=86400)
JOURNAL_SYNC_WRITES = env.bool("JOURNAL_SYNC_WRITES", default=True)
LANCZOS_M = env.int("LANCZOS_M", default=20)
LEARNING_RATE_DYNAMIC = env.bool("LEARNING_RATE_DYNAMIC", default=False)
LEARNING_TENANTS_OVERRIDES = env.str("LEARNING_TENANTS_OVERRIDES", default="")
MEMORY_FAST_ACK = env.bool("MEMORY_FAST_ACK", default=False)
MODE_OPA_POLICY_BUNDLE = env.str("MODE_OPA_POLICY_BUNDLE", default="")
OPA_TIMEOUT_SECONDS = env.float("OPA_TIMEOUT_SECONDS", default=2.0)
ORCHESTRATOR_ROUTING = env.str("ORCHESTRATOR_ROUTING", default="")
ORCHESTRATOR_NAMESPACE = env.str("ORCHESTRATOR_NAMESPACE", default="cog")
OUTBOX_TENANT_QUOTA_LIMIT = env.int("OUTBOX_TENANT_QUOTA_LIMIT", default=1000)
OUTBOX_TENANT_QUOTA_WINDOW = env.int("OUTBOX_TENANT_QUOTA_WINDOW", default=60)
PREDICTOR_ALPHA = env.float("PREDICTOR_ALPHA", default=2.0)
REDIS_DB = env.int("REDIS_DB", default=0)
REQUIRE_EXTERNAL_BACKENDS = env.bool("REQUIRE_EXTERNAL_BACKENDS", default=False)
RETRIEVAL_ALPHA = env.float("RETRIEVAL_ALPHA", default=1.0)
RETRIEVAL_BETA = env.float("RETRIEVAL_BETA", default=0.3)
RETRIEVAL_GAMMA = env.float("RETRIEVAL_GAMMA", default=0.1)
RETRIEVAL_TAU = env.float("RETRIEVAL_TAU", default=0.8)
TAU_ANNEAL_INTERVAL = env.float("TAU_ANNEAL_INTERVAL", default=60.0)
TAU_DECAY_FACTOR = env.float("TAU_DECAY_FACTOR", default=0.95)
TAU_MIN_FLOOR = env.float("TAU_MIN_FLOOR", default=0.1)
TENANT_ID = env.str("TENANT_ID", default="default")
TRUTH_APPR_EPS = env.str("TRUTH_APPR_EPS", default="1e-4")
TRUTH_CHEBYSHEV_K = env.int("TRUTH_CHEBYSHEV_K", default=32)
UTILITY_LAMBDA_MAX = env.float("UTILITY_LAMBDA_MAX", default=5.0)
UTILITY_LAMBDA_MIN = env.float("UTILITY_LAMBDA_MIN", default=0.0)
UTILITY_MU_MAX = env.float("UTILITY_MU_MAX", default=5.0)
UTILITY_MU_MIN = env.float("UTILITY_MU_MIN", default=0.0)
UTILITY_NU_MAX = env.float("UTILITY_NU_MAX", default=5.0)
UTILITY_NU_MIN = env.float("UTILITY_NU_MIN", default=0.0)
WM_UPDATES_MAX_ITEMS = env.int("WM_UPDATES_MAX_ITEMS", default=50)
WM_UPDATES_TTL_SECONDS = env.int("WM_UPDATES_TTL_SECONDS", default=8)
