
import environ

env = environ.Env()

# ============================================================================
# COGNITIVE & MEMORY SETTINGS
# ============================================================================

# --- MEMORY SETTINGS ---
# Memory HTTP service
SOMABRAIN_MEMORY_HTTP_HOST = env.str(
    "SOMABRAIN_MEMORY_HTTP_HOST", default=env.str("MEMORY_HTTP_HOST", default=None)
)
SOMABRAIN_MEMORY_HTTP_PORT = env.int(
    "SOMABRAIN_MEMORY_HTTP_PORT", default=env.int("MEMORY_HTTP_PORT", default=0)
)
SOMABRAIN_MEMORY_HTTP_SCHEME = env.str(
    "SOMABRAIN_MEMORY_HTTP_SCHEME",
    default=env.str("MEMORY_HTTP_SCHEME", default="http"),
)
SOMABRAIN_MEMORY_HTTP_ENDPOINT = env.str(
    "SOMABRAIN_MEMORY_HTTP_ENDPOINT",
    default=env.str("MEMORY_SERVICE_URL", default="http://localhost:9595"),
)
SOMABRAIN_MEMORY_HTTP_TOKEN = env.str(
    "SOMABRAIN_MEMORY_HTTP_TOKEN", default=env.str("SOMA_API_TOKEN", default=None)
)
SOMABRAIN_MEMORY_MAX = env.str("SOMABRAIN_MEMORY_MAX", default="10GB")
MEMORY_DB_PATH = env.str("MEMORY_DB_PATH", default="./data/memory.db")

# Memory Backend Mode Selection (AAAS Feature)
SOMABRAIN_MEMORY_MODE = env.str("SOMABRAIN_MEMORY_MODE", default="http")
if SOMABRAIN_MEMORY_MODE not in ("http", "direct"):
    raise ValueError(
        f"Invalid SOMABRAIN_MEMORY_MODE: {SOMABRAIN_MEMORY_MODE}. "
        "Must be 'http' or 'direct'."
    )
SOMABRAIN_MEMORY_ENABLE_WEIGHTING = env.bool(
    "SOMABRAIN_FF_MEMORY_WEIGHTING",
    default=env.bool("SOMABRAIN_MEMORY_ENABLE_WEIGHTING", default=False),
)
SOMABRAIN_MEMORY_PHASE_PRIORS = env.str("SOMABRAIN_MEMORY_PHASE_PRIORS", default="")
SOMABRAIN_MEMORY_QUALITY_EXP = env.float("SOMABRAIN_MEMORY_QUALITY_EXP", default=1.0)
SOMABRAIN_MEMORY_FAST_ACK = env.bool("SOMABRAIN_MEMORY_FAST_ACK", default=False)

# Memory degradation
SOMABRAIN_MEMORY_DEGRADE_QUEUE = env.bool(
    "SOMABRAIN_MEMORY_DEGRADE_QUEUE", default=True
)
SOMABRAIN_MEMORY_DEGRADE_READONLY = env.bool(
    "SOMABRAIN_MEMORY_DEGRADE_READONLY", default=False
)
SOMABRAIN_MEMORY_DEGRADE_TOPIC = env.str(
    "SOMABRAIN_MEMORY_DEGRADE_TOPIC", default="memory.degraded"
)
SOMABRAIN_MEMORY_HEALTH_POLL_INTERVAL = env.float(
    "SOMABRAIN_MEMORY_HEALTH_POLL_INTERVAL", default=5.0
)
SOMABRAIN_DEBUG_MEMORY_CLIENT = env.bool("SOMABRAIN_DEBUG_MEMORY_CLIENT", default=False)

# Working memory configuration
SOMABRAIN_EMBED_DIM = env.int("EMBED_DIM", default=256)
SOMABRAIN_WM_SIZE = env.int("SOMABRAIN_WM_SIZE", default=64)
SOMABRAIN_WM_RECENCY_TIME_SCALE = env.float(
    "SOMABRAIN_WM_RECENCY_TIME_SCALE", default=1.0
)
SOMABRAIN_WM_RECENCY_MAX_STEPS = env.int("SOMABRAIN_WM_RECENCY_MAX_STEPS", default=1000)
SOMABRAIN_WM_ALPHA = env.float("SOMABRAIN_WM_ALPHA", default=0.6)
SOMABRAIN_WM_BETA = env.float("SOMABRAIN_WM_BETA", default=0.3)
SOMABRAIN_WM_GAMMA = env.float("SOMABRAIN_WM_GAMMA", default=0.1)
SOMABRAIN_WM_SALIENCE_THRESHOLD = env.float(
    "SOMABRAIN_WM_SALIENCE_THRESHOLD", default=0.4
)
SOMABRAIN_WM_PER_COL_MIN_CAPACITY = env.int(
    "SOMABRAIN_WM_PER_COL_MIN_CAPACITY", default=16
)
SOMABRAIN_WM_VOTE_SOFTMAX_FLOOR = env.float(
    "SOMABRAIN_WM_VOTE_SOFTMAX_FLOOR", default=1e-4
)
SOMABRAIN_WM_VOTE_ENTROPY_EPS = env.float("SOMABRAIN_WM_VOTE_ENTROPY_EPS", default=1e-9)
SOMABRAIN_WM_PER_TENANT_CAPACITY = env.int(
    "SOMABRAIN_WM_PER_TENANT_CAPACITY", default=128
)
SOMABRAIN_MTWM_MAX_TENANTS = env.int("SOMABRAIN_MTWM_MAX_TENANTS", default=1000)

# Micro-circuit configuration
SOMABRAIN_MICRO_CIRCUITS = env.int("SOMABRAIN_MICRO_CIRCUITS", default=1)
SOMABRAIN_MICRO_VOTE_TEMPERATURE = env.float(
    "SOMABRAIN_MICRO_VOTE_TEMPERATURE", default=0.25
)
SOMABRAIN_USE_MICROCIRCUITS = env.bool("SOMABRAIN_USE_MICROCIRCUITS", default=False)
SOMABRAIN_MICRO_MAX_TENANTS = env.int("SOMABRAIN_MICRO_MAX_TENANTS", default=1000)

# Tiered memory cleanup
SOMABRAIN_CLEANUP_BACKEND = env.str("SOMABRAIN_CLEANUP_BACKEND", default="milvus")
SOMABRAIN_CLEANUP_TOPK = env.int("SOMABRAIN_CLEANUP_TOPK", default=64)
SOMABRAIN_CLEANUP_HNSW_M = env.int("SOMABRAIN_CLEANUP_HNSW_M", default=32)
SOMABRAIN_CLEANUP_HNSW_EF_CONSTRUCTION = env.int(
    "SOMABRAIN_CLEANUP_HNSW_EF_CONSTRUCTION", default=200
)
SOMABRAIN_CLEANUP_HNSW_EF_SEARCH = env.int(
    "SOMABRAIN_CLEANUP_HNSW_EF_SEARCH", default=128
)

# Scorer weights
SOMABRAIN_SCORER_W_COSINE = env.float("SOMABRAIN_SCORER_W_COSINE", default=0.6)
SOMABRAIN_SCORER_W_FD = env.float("SOMABRAIN_SCORER_W_FD", default=0.25)
SOMABRAIN_SCORER_W_RECENCY = env.float("SOMABRAIN_SCORER_W_RECENCY", default=0.15)
SOMABRAIN_SCORER_WEIGHT_MIN = env.float("SOMABRAIN_SCORER_WEIGHT_MIN", default=0.0)
SOMABRAIN_SCORER_WEIGHT_MAX = env.float("SOMABRAIN_SCORER_WEIGHT_MAX", default=1.0)
SOMABRAIN_SCORER_RECENCY_TAU = env.float("SOMABRAIN_SCORER_RECENCY_TAU", default=32.0)

# Retrieval weights
SOMABRAIN_RETRIEVAL_ALPHA = env.float("SOMABRAIN_RETRIEVAL_ALPHA", default=1.0)
SOMABRAIN_RETRIEVAL_BETA = env.float("SOMABRAIN_RETRIEVAL_BETA", default=0.2)
SOMABRAIN_RETRIEVAL_GAMMA = env.float("SOMABRAIN_RETRIEVAL_GAMMA", default=0.1)
SOMABRAIN_RETRIEVAL_TAU = env.float("SOMABRAIN_RETRIEVAL_TAU", default=0.7)
SOMABRAIN_RECENCY_HALF_LIFE = env.float("SOMABRAIN_RECENCY_HALF_LIFE", default=60.0)
SOMABRAIN_RECENCY_SHARPNESS = env.float("SOMABRAIN_RECENCY_SHARPNESS", default=1.2)
SOMABRAIN_RECENCY_FLOOR = env.float("SOMABRAIN_RECENCY_FLOOR", default=0.05)
SOMABRAIN_DENSITY_TARGET = env.float("SOMABRAIN_DENSITY_TARGET", default=0.2)
SOMABRAIN_DENSITY_FLOOR = env.float("SOMABRAIN_DENSITY_FLOOR", default=0.6)
SOMABRAIN_DENSITY_WEIGHT = env.float("SOMABRAIN_DENSITY_WEIGHT", default=0.35)
SOMABRAIN_TAU_MIN = env.float("SOMABRAIN_TAU_MIN", default=0.4)
SOMABRAIN_TAU_MAX = env.float("SOMABRAIN_TAU_MAX", default=1.2)
SOMABRAIN_TAU_INC_UP = env.float("SOMABRAIN_TAU_INC_UP", default=0.1)
SOMABRAIN_TAU_INC_DOWN = env.float("SOMABRAIN_TAU_INC_DOWN", default=0.05)
SOMABRAIN_DUP_RATIO_THRESHOLD = env.float("SOMABRAIN_DUP_RATIO_THRESHOLD", default=0.5)

# Recall behavior
SOMABRAIN_RECALL_FULL_POWER = env.bool("SOMABRAIN_RECALL_FULL_POWER", default=True)
SOMABRAIN_RECALL_SIMPLE_DEFAULTS = env.bool(
    "SOMABRAIN_RECALL_SIMPLE_DEFAULTS", default=False
)
SOMABRAIN_RECALL_DEFAULT_RERANK = env.str(
    "SOMABRAIN_RECALL_DEFAULT_RERANK", default="auto"
)
SOMABRAIN_RECALL_DEFAULT_PERSIST = env.bool(
    "SOMABRAIN_RECALL_DEFAULT_PERSIST", default=True
)
SOMABRAIN_RECALL_DEFAULT_RETRIEVERS = env.str(
    "SOMABRAIN_RECALL_DEFAULT_RETRIEVERS", default="vector,wm,graph,lexical"
)

# Salience configuration
SOMABRAIN_SALIENCE_METHOD = env.str("SOMABRAIN_SALIENCE_METHOD", default="dense")
SOMABRAIN_SALIENCE_FD_RANK = env.int("SOMABRAIN_SALIENCE_FD_RANK", default=128)
SOMABRAIN_SALIENCE_FD_DECAY = env.float("SOMABRAIN_SALIENCE_FD_DECAY", default=0.9)
SOMABRAIN_SALIENCE_W_NOVELTY = env.float("SOMABRAIN_SALIENCE_W_NOVELTY", default=0.6)
SOMABRAIN_SALIENCE_W_ERROR = env.float("SOMABRAIN_SALIENCE_W_ERROR", default=0.4)
SOMABRAIN_SALIENCE_THRESHOLD_STORE = env.float(
    "SOMABRAIN_SALIENCE_THRESHOLD_STORE", default=0.5
)
SOMABRAIN_SALIENCE_THRESHOLD_ACT = env.float(
    "SOMABRAIN_SALIENCE_THRESHOLD_ACT", default=0.7
)
SOMABRAIN_SALIENCE_HYSTERESIS = env.float("SOMABRAIN_SALIENCE_HYSTERESIS", default=0.1)
SOMABRAIN_SALIENCE_FD_WEIGHT = env.float("SOMABRAIN_SALIENCE_FD_WEIGHT", default=0.25)
SOMABRAIN_SALIENCE_FD_ENERGY_FLOOR = env.float(
    "SOMABRAIN_SALIENCE_FD_ENERGY_FLOOR", default=0.9
)
SOMABRAIN_SALIENCE_SOFT_TEMPERATURE = env.float(
    "SOMABRAIN_SALIENCE_SOFT_TEMPERATURE", default=0.1
)
SOMABRAIN_USE_SOFT_SALIENCE = env.bool("SOMABRAIN_USE_SOFT_SALIENCE", default=False)

# Feature toggles
SOMABRAIN_USE_HRR = env.bool("SOMABRAIN_USE_HRR", default=False)
SOMABRAIN_USE_META_BRAIN = env.bool("SOMABRAIN_USE_META_BRAIN", default=False)
SOMABRAIN_USE_EXEC_CONTROLLER = env.bool("SOMABRAIN_USE_EXEC_CONTROLLER", default=False)
SOMABRAIN_USE_DRIFT_MONITOR = env.bool("SOMABRAIN_USE_DRIFT_MONITOR", default=False)
SOMABRAIN_USE_SDR_PREFILTER = env.bool("SOMABRAIN_USE_SDR_PREFILTER", default=False)
SOMABRAIN_USE_GRAPH_AUGMENT = env.bool("SOMABRAIN_USE_GRAPH_AUGMENT", default=False)
SOMABRAIN_USE_HRR_FIRST = env.bool("SOMABRAIN_USE_HRR_FIRST", default=False)

# Graph configuration
SOMABRAIN_GRAPH_HOPS = env.int("SOMABRAIN_GRAPH_HOPS", default=2)
SOMABRAIN_GRAPH_LIMIT = env.int("SOMABRAIN_GRAPH_LIMIT", default=20)
SOMABRAIN_GRAPH_FILE = env.str("SOMABRAIN_GRAPH_FILE", default=None)
SOMABRAIN_GRAPH_FILE_ACTION = env.str("SOMABRAIN_GRAPH_FILE_ACTION", default=None)
SOMABRAIN_GRAPH_FILE_AGENT = env.str("SOMABRAIN_GRAPH_FILE_AGENT", default=None)

# Planner / graph walk
SOMABRAIN_PLANNER_RWR_STEPS = env.int("SOMABRAIN_PLANNER_RWR_STEPS", default=20)
SOMABRAIN_PLANNER_RWR_RESTART = env.float("SOMABRAIN_PLANNER_RWR_RESTART", default=0.15)
SOMABRAIN_PLANNER_RWR_MAX_NODES = env.int(
    "SOMABRAIN_PLANNER_RWR_MAX_NODES", default=128
)
SOMABRAIN_PLANNER_RWR_EDGES_PER_NODE = env.int(
    "SOMABRAIN_PLANNER_RWR_EDGES_PER_NODE", default=32
)
SOMABRAIN_PLANNER_RWR_MAX_ITEMS = env.int("SOMABRAIN_PLANNER_RWR_MAX_ITEMS", default=5)

# --- COGNITIVE SETTINGS ---
# HRR configuration
SOMABRAIN_HRR_DIM = env.int("SOMABRAIN_HRR_DIM", default=8192)
SOMABRAIN_HRR_DTYPE = env.str("SOMABRAIN_HRR_DTYPE", default="float32")
SOMABRAIN_HRR_RENORM = env.bool("SOMABRAIN_HRR_RENORM", default=True)
SOMABRAIN_HRR_VECTOR_FAMILY = env.str("SOMABRAIN_HRR_VECTOR_FAMILY", default="bhdc")
SOMABRAIN_BHDC_SPARSITY = env.float("SOMABRAIN_BHDC_SPARSITY", default=0.1)

# SDR configuration
SOMABRAIN_SDR_BITS = env.int("SOMABRAIN_SDR_BITS", default=2048)
SOMABRAIN_SDR_DENSITY = env.float("SOMABRAIN_SDR_DENSITY", default=0.03)
SOMABRAIN_SDR_DIM = env.int("SOMABRAIN_SDR_DIM", default=16384)
SOMABRAIN_SDR_SPARSITY = env.float("SOMABRAIN_SDR_SPARSITY", default=0.01)

# Context configuration
SOMABRAIN_CONTEXT_BUDGET_TOKENS = env.int(
    "SOMABRAIN_CONTEXT_BUDGET_TOKENS", default=2048
)
SOMABRAIN_MAX_SUPERPOSE = env.int("SOMABRAIN_MAX_SUPERPOSE", default=32)
SOMABRAIN_DEFAULT_WM_SLOTS = env.int("SOMABRAIN_DEFAULT_WM_SLOTS", default=12)

# Determinism and seeding
SOMABRAIN_GLOBAL_SEED = env.int("SOMABRAIN_GLOBAL_SEED", default=42)
SOMABRAIN_DETERMINISM = env.bool("SOMABRAIN_DETERMINISM", default=True)

# Quotas
SOMABRAIN_QUOTA_TENANT = env.int("SOMABRAIN_QUOTA_TENANT", default=10000)
SOMABRAIN_QUOTA_TOOL = env.int("SOMABRAIN_QUOTA_TOOL", default=1000)
SOMABRAIN_QUOTA_ACTION = env.int("SOMABRAIN_QUOTA_ACTION", default=500)

# Quantum layer
SOMABRAIN_QUANTUM_DIM = env.int("SOMABRAIN_QUANTUM_DIM", default=2048)
SOMABRAIN_QUANTUM_SPARSITY = env.float("SOMABRAIN_QUANTUM_SPARSITY", default=0.1)

# Planning configuration
SOMABRAIN_USE_PLANNER = env.bool("SOMABRAIN_USE_PLANNER", default=False)
SOMABRAIN_USE_FOCUS_STATE = env.bool("SOMABRAIN_USE_FOCUS_STATE", default=True)
SOMABRAIN_PLAN_MAX_STEPS = env.int("SOMABRAIN_PLAN_MAX_STEPS", default=5)
SOMABRAIN_PLANNER_BACKEND = env.str("SOMABRAIN_PLANNER_BACKEND", default="bfs")

# Sleep system
SOMABRAIN_ENABLE_SLEEP = env.bool("SOMABRAIN_ENABLE_SLEEP", default=True)
SOMABRAIN_CONSOLIDATION_ENABLED = env.bool(
    "SOMABRAIN_CONSOLIDATION_ENABLED", default=True
)
SOMABRAIN_SLEEP_INTERVAL_SECONDS = env.int(
    "SOMABRAIN_SLEEP_INTERVAL_SECONDS", default=3600
)
SOMABRAIN_CONSOLIDATION_TIMEOUT_S = env.float(
    "SOMABRAIN_CONSOLIDATION_TIMEOUT_S", default=30.0
)
SOMABRAIN_NREM_BATCH_SIZE = env.int("SOMABRAIN_NREM_BATCH_SIZE", default=16)
SOMABRAIN_MAX_SUMMARIES_PER_CYCLE = env.int(
    "SOMABRAIN_MAX_SUMMARIES_PER_CYCLE", default=3
)
SOMABRAIN_REM_RECOMB_RATE = env.float("SOMABRAIN_REM_RECOMB_RATE", default=0.2)
SLEEP_K0 = env.int("SLEEP_K0", default=10)
SLEEP_T0 = env.float("SLEEP_T0", default=1.0)
SLEEP_TAU0 = env.float("SLEEP_TAU0", default=0.1)
SLEEP_ETA0 = env.float("SLEEP_ETA0", default=0.01)
SLEEP_LAMBDA0 = env.float("SLEEP_LAMBDA0", default=0.5)
SLEEP_B0 = env.float("SLEEP_B0", default=1.0)
SLEEP_K_MIN = env.int("SLEEP_K_MIN", default=5)
SLEEP_T_MIN = env.float("SLEEP_T_MIN", default=0.5)
SLEEP_ALPHA_K = env.float("SLEEP_ALPHA_K", default=0.1)
SLEEP_ALPHA_T = env.float("SLEEP_ALPHA_T", default=0.05)
SLEEP_ALPHA_TAU = env.float("SLEEP_ALPHA_TAU", default=0.05)
SLEEP_ALPHA_ETA = env.float("SLEEP_ALPHA_ETA", default=0.01)
SLEEP_BETA_B = env.float("SLEEP_BETA_B", default=0.1)

# Rate limiting
SOMABRAIN_RATE_RPS = env.int("SOMABRAIN_RATE_RPS", default=1000)
SOMABRAIN_RATE_BURST = env.int("SOMABRAIN_RATE_BURST", default=2000)
SOMABRAIN_WRITE_DAILY_LIMIT = env.int("SOMABRAIN_WRITE_DAILY_LIMIT", default=100000)

# Learning & Adaptation Settings
SOMABRAIN_TAU_DECAY_ENABLED = env.bool("SOMABRAIN_TAU_DECAY_ENABLED", default=False)
SOMABRAIN_TAU_DECAY_RATE = env.float("SOMABRAIN_TAU_DECAY_RATE", default=0.0)
SOMABRAIN_TAU_ANNEAL_MODE = env.str("SOMABRAIN_TAU_ANNEAL_MODE", default=None)
SOMABRAIN_TAU_ANNEAL_RATE = env.float("SOMABRAIN_TAU_ANNEAL_RATE", default=0.0)
SOMABRAIN_TAU_ANNEAL_STEP_INTERVAL = env.int(
    "SOMABRAIN_TAU_ANNEAL_STEP_INTERVAL", default=0
)
SOMABRAIN_ENTROPY_CAP_ENABLED = env.bool("SOMABRAIN_ENTROPY_CAP_ENABLED", default=False)
SOMABRAIN_ENTROPY_CAP = env.float("SOMABRAIN_ENTROPY_CAP", default=0.0)
SOMABRAIN_LEARNING_RATE_DYNAMIC = env.bool(
    "SOMABRAIN_LEARNING_RATE_DYNAMIC", default=False
)

SOMABRAIN_UTILITY_LAMBDA = env.float("SOMABRAIN_UTILITY_LAMBDA", default=1.0)
SOMABRAIN_UTILITY_MU = env.float("SOMABRAIN_UTILITY_MU", default=0.1)
SOMABRAIN_UTILITY_NU = env.float("SOMABRAIN_UTILITY_NU", default=0.05)
SOMABRAIN_ADAPTATION_GAIN_ALPHA = env.float(
    "SOMABRAIN_ADAPTATION_GAIN_ALPHA", default=1.0
)
SOMABRAIN_ADAPTATION_GAIN_GAMMA = env.float(
    "SOMABRAIN_ADAPTATION_GAIN_GAMMA", default=-0.5
)
SOMABRAIN_ADAPTATION_GAIN_LAMBDA = env.float(
    "SOMABRAIN_ADAPTATION_GAIN_LAMBDA", default=1.0
)
SOMABRAIN_ADAPTATION_GAIN_MU = env.float("SOMABRAIN_ADAPTATION_GAIN_MU", default=-0.25)
SOMABRAIN_ADAPTATION_GAIN_NU = env.float("SOMABRAIN_ADAPTATION_GAIN_NU", default=-0.25)

SOMABRAIN_ADAPTATION_ALPHA_MIN = env.float(
    "SOMABRAIN_ADAPTATION_ALPHA_MIN", default=0.1
)
SOMABRAIN_ADAPTATION_ALPHA_MAX = env.float(
    "SOMABRAIN_ADAPTATION_ALPHA_MAX", default=5.0
)
SOMABRAIN_ADAPTATION_GAMMA_MIN = env.float(
    "SOMABRAIN_ADAPTATION_GAMMA_MIN", default=0.0
)
SOMABRAIN_ADAPTATION_GAMMA_MAX = env.float(
    "SOMABRAIN_ADAPTATION_GAMMA_MAX", default=1.0
)
SOMABRAIN_ADAPTATION_LAMBDA_MIN = env.float(
    "SOMABRAIN_ADAPTATION_LAMBDA_MIN", default=0.1
)
SOMABRAIN_ADAPTATION_LAMBDA_MAX = env.float(
    "SOMABRAIN_ADAPTATION_LAMBDA_MAX", default=5.0
)
SOMABRAIN_ADAPTATION_MU_MIN = env.float("SOMABRAIN_ADAPTATION_MU_MIN", default=0.01)
SOMABRAIN_ADAPTATION_MU_MAX = env.float("SOMABRAIN_ADAPTATION_MU_MAX", default=5.0)
SOMABRAIN_ADAPTATION_NU_MIN = env.float("SOMABRAIN_ADAPTATION_NU_MIN", default=0.01)
SOMABRAIN_ADAPTATION_NU_MAX = env.float("SOMABRAIN_ADAPTATION_NU_MAX", default=5.0)

# Predictor configuration
SOMABRAIN_PREDICTOR_PROVIDER = env.str("SOMABRAIN_PREDICTOR_PROVIDER", default="mahal")
SOMABRAIN_PREDICTOR_DIM = env.int("SOMABRAIN_PREDICTOR_DIM", default=16)
SOMABRAIN_PREDICTOR_ALPHA = env.float("SOMABRAIN_PREDICTOR_ALPHA", default=2.0)
SOMABRAIN_PREDICTOR_GAMMA = env.float("SOMABRAIN_PREDICTOR_GAMMA", default=-0.5)

# LLM endpoint
SOMABRAIN_LLM_ENDPOINT = env.str("SOMABRAIN_LLM_ENDPOINT", default=None)

# --- OAK (ROAMDP) SETTINGS ---
ENABLE_OAK = env.bool("ENABLE_OAK", default=False)
OAK_BASE_UTILITY = env.float("OAK_BASE_UTILITY", default=1.0)
OAK_UTILITY_FACTOR = env.float("OAK_UTILITY_FACTOR", default=0.1)
OAK_TAU_MIN = env.float("OAK_TAU_MIN", default=30.0)
OAK_TAU_MAX = env.float("OAK_TAU_MAX", default=300.0)
OAK_PLAN_MAX_OPTIONS = env.int("OAK_PLAN_MAX_OPTIONS", default=10)
OAK_SIMILARITY_THRESHOLD = env.float("OAK_SIMILARITY_THRESHOLD", default=0.8)
OAK_REWARD_THRESHOLD = env.float("OAK_REWARD_THRESHOLD", default=0.5)
OAK_NOVELTY_THRESHOLD = env.float("OAK_NOVELTY_THRESHOLD", default=0.2)
OAK_GAMMA = env.float("OAK_GAMMA", default=0.99)
OAK_ALPHA = env.float("OAK_ALPHA", default=0.1)
OAK_KAPPA = env.float("OAK_KAPPA", default=1.0)
