
import environ

env = environ.Env()

# ============================================================================
# NEUROMODULATOR SETTINGS
# ============================================================================

# Neuromodulator settings
SOMABRAIN_NEURO_DOPAMINE_BASE = env.float("SOMABRAIN_NEURO_DOPAMINE_BASE", default=0.4)
SOMABRAIN_NEURO_SEROTONIN_BASE = env.float(
    "SOMABRAIN_NEURO_SEROTONIN_BASE", default=0.5
)
SOMABRAIN_NEURO_NORAD_BASE = env.float("SOMABRAIN_NEURO_NORAD_BASE", default=0.0)
SOMABRAIN_NEURO_ACETYL_BASE = env.float("SOMABRAIN_NEURO_ACETYL_BASE", default=0.0)

# Neuromodulator Adaptive Bounds
SOMABRAIN_NEURO_DOPAMINE_MIN = env.float("SOMABRAIN_NEURO_DOPAMINE_MIN", default=0.2)
SOMABRAIN_NEURO_DOPAMINE_MAX = env.float("SOMABRAIN_NEURO_DOPAMINE_MAX", default=0.8)
SOMABRAIN_NEURO_DOPAMINE_LR = env.float("SOMABRAIN_NEURO_DOPAMINE_LR", default=0.01)

SOMABRAIN_NEURO_SEROTONIN_MIN = env.float("SOMABRAIN_NEURO_SEROTONIN_MIN", default=0.0)
SOMABRAIN_NEURO_SEROTONIN_MAX = env.float("SOMABRAIN_NEURO_SEROTONIN_MAX", default=1.0)
SOMABRAIN_NEURO_SEROTONIN_LR = env.float("SOMABRAIN_NEURO_SEROTONIN_LR", default=0.01)

SOMABRAIN_NEURO_NORAD_MIN = env.float("SOMABRAIN_NEURO_NORAD_MIN", default=0.0)
SOMABRAIN_NEURO_NORAD_MAX = env.float("SOMABRAIN_NEURO_NORAD_MAX", default=0.1)
SOMABRAIN_NEURO_NORAD_LR = env.float("SOMABRAIN_NEURO_NORAD_LR", default=0.01)

SOMABRAIN_NEURO_ACETYL_MIN = env.float("SOMABRAIN_NEURO_ACETYL_MIN", default=0.0)
SOMABRAIN_NEURO_ACETYL_MAX = env.float("SOMABRAIN_NEURO_ACETYL_MAX", default=0.1)
SOMABRAIN_NEURO_ACETYL_LR = env.float("SOMABRAIN_NEURO_ACETYL_LR", default=0.01)

# Neuromodulator Feedback Parameters
SOMABRAIN_NEURO_DOPAMINE_REWARD_BOOST = env.float(
    "SOMABRAIN_NEURO_DOPAMINE_REWARD_BOOST", default=0.1
)
SOMABRAIN_NEURO_DOPAMINE_BIAS = env.float("SOMABRAIN_NEURO_DOPAMINE_BIAS", default=0.05)
SOMABRAIN_NEURO_URGENCY_FACTOR = env.float(
    "SOMABRAIN_NEURO_URGENCY_FACTOR", default=0.02
)
SOMABRAIN_NEURO_LATENCY_FLOOR = env.float("SOMABRAIN_NEURO_LATENCY_FLOOR", default=0.1)
SOMABRAIN_NEURO_LATENCY_SCALE = env.float("SOMABRAIN_NEURO_LATENCY_SCALE", default=0.01)
SOMABRAIN_NEURO_MEMORY_FACTOR = env.float("SOMABRAIN_NEURO_MEMORY_FACTOR", default=0.02)
SOMABRAIN_NEURO_ACCURACY_SCALE = env.float(
    "SOMABRAIN_NEURO_ACCURACY_SCALE", default=0.05
)
