name: branch-image

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute branch tags
        id: meta
        run: |
          ref="${GITHUB_REF_NAME}"
          # sanitize: lowercase, replace invalid chars with '-'
          sanitized=$(printf "%s" "$ref" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g' | sed -E 's/^-+|+-$//g')
          shortsha="${GITHUB_SHA::7}"
          echo "branch=$sanitized" >> "$GITHUB_OUTPUT"
          echo "short=$shortsha" >> "$GITHUB_OUTPUT"
          echo "tags=ghcr.io/${GITHUB_REPOSITORY}:$sanitized-latest,ghcr.io/${GITHUB_REPOSITORY}:$sanitized-$shortsha" >> "$GITHUB_OUTPUT"

      - name: Build and push (branch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.ref.name=${{ steps.meta.outputs.branch }}
