name: Hybrid CI

on:
  push:
    branches: [ main, math-upgrade ]
  pull_request:
    branches: [ main ]

jobs:
  hybrid-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt || true
          pip install numpy pytest pyyaml || true
      - name: Run hybrid training example
        run: |
          python examples/train_role.py
